### ISSUE TITLE
Automate creating test users for relenv

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#1002]
The functional tests run using a test user: `psu4test` 

This user needs to be created in the FIDC instance; the user has been created manually previously.

Add fr-platform-config to create this user via the cs_config_manager tool.

**Comment by dbadham-fr** [comment]
New user configuration needs to be added here:
https://github.com/ForgeCloud/secure-api-gateway-relenv-deployments/tree/main/ob-sandbox-v1/id-cloud-config/service-objects/alpha_user

Note: this user is for SAPI-G testing and is not needed in customer deployments.

**Comment by shaunharrisonFR** [comment]
I've tried pulling from nightly and ob-sandbox-v1 but not seeing anything in there for psu4test while using the alpha-2 branch

The user must exist in both instances so maybe the config tool doesn't know to pull it down?
