### ISSUE TITLE
Test User Data API feature to create PSU users and push the related account data

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#1005]
## Description
A feature to create `PSU` users and push the related account data.

This feature has been defined to create `PSU` users (bank customers) and the related account data for those `PSU` users, so that the customers can feed the platform with his own users and account data for test purposes.

It's expected the creation of several `PSU` users with their several related account data.

## Spec definition
- Needs to support the creation of several users and their related account data.
- A well defined json file user data
**Identity Cloud Platform**
- The user needs to be pushed to `Identity Cloud platform`, using cs-config-manager application, before push related account data.
**Test bank facility**
See comment below https://github.com/SecureApiGateway/SecureApiGateway/issues/1005#issuecomment-1578509765

**Comment by jorgesanchezperez** [comment]
### Notes
Currently we have two different ways to push user data:
- Making a POST request to `generate` [`/admin/fake-data/generate`] endpoint, so that the platform creates random user data
- Making a POST request to `import` [`/admin/data/user`] endpoint providing a json that contains the user data to be pushed.

## Diff behaviours
The generate endpoint creates the data using the `userId` value, (UUID) provided in the request, as `userID`.
```json
{
  "_id": "01233243245676",
  "userID": "4737f9f9-fa0a-4159-bc61-7da31542e624",
  "account": {
    "accounts": [...]
  },
  "_class": "com.forgerock.sapi.gateway.ob.uk.rs.server.persistence.document.account.FRAccount"
}
```
The import endpoint push the data using the `userName` value, userName field provided in the user data json payload provided in the request, as `userID`
```json
{
  "_id": "01233243245676",
  "userID": "user name",
  "account": {
    "accounts": [...]
  },
  "_class": "com.forgerock.sapi.gateway.ob.uk.rs.server.persistence.document.account.FRAccount"
}
```
| endpoint | userId value populated | used for |
|---|---|---|
| generate | user ID (UUID) | populate `psu4test` user data for internal functional tests |
| import | user Name | push customer test facility user data |

This difference makes complicate search the accounts by userID when the value stored in the `userID` can be a random user name with spaces or user Id that represents an standard UUID, so that we need to store the same kind of value in the `userID` field.

How the user data json files are provided by the customer, currently the customer provide these files with the user name with no user id. So that we need to fix the creation data

**Comment by BohoCode** [comment]
Of these solutions I think the best solution will be to:

- modify the `/admin/data/user` controller to use the userName in the provided json payload, and then look up the user in IDM and obtain the userID uuid from that record.
- In the controller use the userID from the IDM user record to populate the userID in the mongo data records created.

**NOTE**: We need to ensure after this work that all the data is still populated in the consent UIs correctly.

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/1005?planning-poker) with Zenhub @jorgesanchezperez @dbadham-fr

**Comment by jorgesanchezperez** [comment]
https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/389
- Updated the Groovy Script `RepoUser.groovy` Used as script filter in the route `60-internal-repo` to retrieve the user data from IDM.
- To support `_queryFilter by username` together with current search by `user ID`

**Comment by jorgesanchezperez** [comment]
Updated DataApi `admin/data/user` to validate that the user has been created in the Identity Cloud Platform before push the user data.

**Trace in Test Facility Bank**
```shell
2023-06-14 15:29:56.228 DEBUG 1 --- [nio-8080-exec-2] .g.o.u.r.s.w.DisabledEndpointInterceptor : Request URI /admin/data/user is not disabled in RS config. Allowed to proceed.
2023-06-14 15:29:56.318 DEBUG 1 --- [nio-8080-exec-2] c.f.s.g.o.u.r.c.c.s.UserClientService    : (UserServiceClient#request) request the user details from platform: http://ig:80/repo/users?_queryFilter=userName+eq+"llc001"
2023-06-14 15:29:56.354 ERROR 1 --- [nio-8080-exec-2] c.f.s.g.o.u.r.s.a.a.d.DataApiController  : Status: 404 NOT_FOUND, reason: 404 Not Found: [{ "error":"User details not found"}]
2023-06-14 15:29:56.355 DEBUG 1 --- [nio-8080-exec-2] c.f.s.g.o.u.r.s.e.GlobalExceptionHandler : Error in admin data user API, reason 404 Not Found: [{ "error":"User details not found"}]
2023-06-14 15:30:05.285 DEBUG 1 --- [nio-8080-exec-6] .g.o.u.r.s.w.DisabledEndpointInterceptor : Request URI /admin/data/user/has-data is not disabled in RS config. Allowed to proceed.
```

**Catch the error response in the pushUserData.sh shell script**
```shell
./pushUserData.sh "har001 llc001"

Pushing har001 user data to test-facility-bank:8080

Deleting user data for har001

Http response to delete: 200
Successfully deleted har001's data
Found data files for har001;
ingest/har001.json
Directory 'ingested' to store the responses already exists.

Push data for ingest/har001.json

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  277k    0   174  100  277k    120   192k  0:00:01  0:00:01 --:--:--  192k
CODE 404

Failed to create har001's data, reason 404

HTTP/1.1 404
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 14 Jun 2023 15:29:56 GMT

{"Code":"NOT_FOUND","Id":null,"Message":"Not Found","Errors":[{"ErrorCode":null,"Message":"404 Not Found: [{ \"error\":\"User details not found\"}]","Path":null,"Url":null}]}

Pushing llc001 user data to test-facility-bank:8080

Deleting user data for llc001

Http response to delete: 200
Successfully deleted llc001's data
Found data files for llc001;
ingest/llc001.json
Directory 'ingested' to store the responses already exists.

Push data for ingest/llc001.json

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  288k    0   174  100  287k   1315  2175k --:--:-- --:--:-- --:--:-- 2181k
CODE 404

Failed to create llc001's data, reason 404

HTTP/1.1 404
Content-Type: application/json
Transfer-Encoding: chunked
Date: Wed, 14 Jun 2023 15:29:56 GMT

{"Code":"NOT_FOUND","Id":null,"Message":"Not Found","Errors":[{"ErrorCode":null,"Message":"404 Not Found: [{ \"error\":\"User details not found\"}]","Path":null,"Url":null}]}
```
