### ISSUE TITLE
Apply config changes required for RCS Consent Store to relenv deployment

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#1016]
https://github.com/SecureApiGateway/sapig-openbanking-uk-developer-envs/pull/52 needs applying to relenv when the Consent Store feature is released.

TO DO - review any other config changes required.

**Comment by shaunharrisonFR** [comment]
This PR probably applies to this ticket - https://github.com/SecureApiGateway/SecureApiGateway/issues/1034
