### ISSUE TITLE
Can we protect the mongodb persistent disk in relenv

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureApiGateway/SecureApiGateway#1017]
So the disk is not created via terraform, it is created when the mongodb helm chart is ran

This means that helm will not delete the disk when a helm uninstall runs as there is the following annotation 

`kubernetes.io/pvc-protection`

However, if terraform is to run, then the disk _would_ be deleted as the cluster itself would be removed. 

If we want to backup the data on the disks, we should look to copying the data to a cloud bucket , thoughts on this @BohoCode @dbadham-fr @jorgesanchezperez

**Comment by dbadham-fr** [comment]
Might be interesting to try out the GKE backup support for taking a snapshot of a disk. Rather than having a custom container/script that copies data out of Mongo and another which imports.

**Comment by shaunharrisonFR** [comment]
Best way to do this is to simply create a snapshot of the disk like @dbadham-fr mentioned in the comment, we can simply create a schedule in the UI to back the disk up X amount of times, and even delete the snapshots after 14 days so we don't incur costs, this would save us having to move the data to a cloud bucket and what not and no scripting required so seems the best option, thoughts @BohoCode ?

**Comment by shaunharrisonFR** [comment]
Google have a new backup feature for kubernetes that gives us the option to backup a persistent disk 
 
[See docs](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/concepts/backup-for-gke?_gl=1*1ox4val*_ga*NTU3NTQ1NzM3LjE2NjE4NjIxMzc.*_ga_WH2QY8WWF5*MTY5NTgwMzczOC4xMjguMS4xNjk1ODAzNzM4LjAuMC4w&_ga=2.102922436.-557545737.1661862137&_gac=1.62023134.1692172689.CjwKCAjw5_GmBhBIEiwA5QSMxPH-QW6da5VlzUuPp-R3SSIJDLUblN2JYHDbJuGyzAZDt2rmDNsVxxoC8ysQAvD_BwE)

**Comment by shaunharrisonFR** [comment]
With the change to a stateful set in #1157 the disks for mongodb are now protected even from a terreform destroy 

This was spotted by ITSS who noticed the quotas for SSD were all used up and had to manually remove the mongo disks that were not destroyed during the usual infra teardown

Ticket: https://bugster.forgerock.org/jira/secure/RapidBoard.jspa?rapidView=923&projectKey=SAPIG&view=detail&selectedIssue=SAPIG-280 which will be brought over to FR once confirmed working
