### ISSUE TITLE
[devops] Deployment operation improvements

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#234]
### Description
Improvements suggestions for deployments:

#### Deployments (helm charts, kubernetes templates...)
Deployment operations improvements:
- [ ] Improve (sbat-infra: nginx helm chart) nginx logs
- [ ] Fix duplication properties
- [ ] Delete unused properties or deprecated properties through deployments
- [ ] Change the host names in `nginx`: (_It Can be skip if we deploy an identity platform cdk/cdm on each namespace/environment_)
        - obdemo.`${nampespace}`.forgerock.financial to ig.`${namespace}`.forgerock.financial to identify properly the endpoint service
        - iam.dev.forgerock.financial to cdk.forgerock.financial or cdm.forgerock.financial
- [x] deploy the identity cloud CDK or CDM for each namespace, now is deployed the CDK only in cdk namespace and all other developer namespaces/environment use the same identity platform cdk/cdm instance.
        - Create the register in `nginx` for cdk.`${namespace}`.forgerock.financial or cdm.`${namespace}`.forgerock.financial
 - [ ] Review the deployment documentation
 - [x] https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/226
#### ci/cd pipelines and actions
- [x] Review functional test step to run the tests properly against the environments.

**Comment by BohoCode** [comment]
Old an no longer relevant
