### ISSUE TITLE
IG repository endpoint security vulnerability

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#239]
**Describe the bug**
We have a route to catch the requests:
- `/repo/consents/{{intentId}}`
- `/repo/apiclients/{{clientId}}`
- `/repo/users/{{userId}}`

But anybody can call that endpoint to obtain the objects because doesn't have any filter to check the authorization header token or similar.

**To Reproduce**
call any endpoint from the above with a correct id to obtain the object.

**Expected behaviour**
Reject the request when isn't authorize

**Current behaviour**
No there is any security implementation to reject a no authorize request.

**Comment by dbadham-fr** [comment]
Below are some example curl commands which demonstrate the issue, replace the environment portion of the URL and id of the object as required:

Get Account Access Intent:
```
curl https://obdemo.dbadham-fr.forgerock.financial/repo/consents/AAC_c0715220-e716-4f31-8336-20cd3bc893ed

# Response:
{"id":"AAC_c0715220-e716-4f31-8336-20cd3bc893ed","data":{"Permissions":["ReadAccountsDetail"],"ExpirationDateTime":null,"TransactionFromDateTime":null,"TransactionToDateTime":null,"ConsentId":"AAC_c0715220-e716-4f31-8336-20cd3bc893ed","Status":"Authorised","CreationDateTime":"2022-10-06T08:13:47.450Z","StatusUpdateDateTime":"2022-10-06T08:13:53.175Z"},"Data":{"Permissions":["ReadAccountsDetail"],"ExpirationDateTime":null,"TransactionFromDateTime":null,"TransactionToDateTime":null,"ConsentId":"AAC_c0715220-e716-4f31-8336-20cd3bc893ed","Status":"Authorised","CreationDateTime":"2022-10-06T08:13:47.450Z","StatusUpdateDateTime":"2022-10-06T08:13:53.175Z"},"accountIds":null,"resourceOwnerUsername":"999ad0a8-d3bc-4b78-b82f-35914c8e75be","oauth2ClientId":"8009202a-9a17-4570-b94d-f5270c1cbbf3","oauth2ClientName":"Automating-testing"}
```

Get user data:
```
 curl https://obdemo.dbadham-fr.forgerock.financial/repo/users/999ad0a8-d3bc-4b78-b82f-35914c8e75be

# Response:
{"id":"999ad0a8-d3bc-4b78-b82f-35914c8e75be","userName":"psu4test","givenName":"PSU","surname":"Payment Services User","mail":"psu@acme.com","accountStatus":"active"}
```

You can also PATCH intents to update them as part of the consent approval flow i.e. change the status, add payment related fields etc

**Comment by dbadham-fr** [comment]
We briefly discussed this during sprint planning.

@jorgesanchezperez suggested that RS and RCS need to use an IDM REST API client library to fetch the data they require from IDM.

I think this is a sensible approach.

A java lib can be written to fetch the IDM data.

RS and RCS will each need an OAuth2 client configured in AM in order to get access tokens to call IDM (to do the same thing that the IDMClientHandler does in IG config)

**Comment by dbadham-fr** [comment]
The disadvantage of the above approach is that it is likely all throw away work. When we move the consent store from IDM to a database (mongo), then an alternative implementation is needed. If we were to implement the IDM REST API client then it would be a minimum viable product implementation, so it is unlikely that any of the work will be reusable.

An alternative, tactical approach, is to remove the [/repo ingress rule](https://github.com/SecureApiGateway/sapig-openbanking-uk-developer-envs/blob/master/kustomize/base/7.1.0/ingress/ingress.yaml#L54-L60). This means that the IG route will only be accessible by internal traffic.

RS and RCS will then need to use the internal IG k8s address when making calls to this API.

We can also investigate if we can protect this internal call with an access token.

This should provide enough security for a v1 release, and will be much quicker to implement.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/239?planning-poker) with Zenhub @dbadham-fr @shaunharrisonFR

**Comment by dbadham-fr** [comment]
Review with @BohoCode 

The ingress rule for /repo has been removed, only internal traffic can access the IG route /repo

It would be nice to add an access_token to protect this flow for belt and braces, but may not be necessary for v1.
