### ISSUE TITLE
The Authorization server must support PKCE rfe 7636

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#243]
# Description
According to FAPI part 1 v1.0 the Authorization server shall require RFC7636 with S256 as the code challenge method

## Reference documents
FAPI document;
- See point 7 [here](https://openid.net/specs/openid-financial-api-part-1-1_0.html#authorization-server)
- RFC 7636, 'Proof Key for Code Exchange by OAuth Public Clients';  [here](https://datatracker.ietf.org/doc/html/rfc7636)
- AM docs; [here](https://backstage.forgerock.com/docs/am/7.1/oauth2-guide/oauth2-authz-grant-pkce.html#oauth2-authz-grant-pkce)
- Valid config values; [Global Services Config](https://backstage.forgerock.com/docs/am/7.1/reference/global-services-configuration.html#global-oauth-oidc)

**To Reproduce**
Steps to reproduce the behaviour:

1.  Login to the native AM console [here](https://openam-forgerock-securebankingaccelerato.forgeblocks.com/am/ui-admin/#realms/%2Falpha/services/edit/oauth-oidc)
2.  See the `Code Verifier Parameter Required` setting. 
3.  This is currently set to Never. 

**Expected behaviour**
This should be set such that the Identity Cloud becomes configured to support rfe 7636.

**Current behaviour**
A code verification parameter is not mandated.

# Tasks
- [ ] Modify the functional tests and postman to support pkce 

### Release Notes

Affected App: X

Description: X
<end release notes>

**Comment by dbadham-fr** [comment]
I think we need to review this issue, as it is referencing the FAPI baseline spec and public clients which we do not support.

PKCE is optional for confidential clients in the FAPI advanced spec. Only if PAR is being used must they use PKCE. According to the AM docs, it will require PKCE params when a par request is being made: https://backstage.forgerock.com/docs/am/7.2/oauth2-guide/oauth2-par-endpoint.html

A customer may decide that they wish to enforce PKCE for all requests, but I don't think we want to apply this configuration by default.

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/243?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez

**Comment by dbadham-fr** [comment]
No configuration changes in AM have been required.

When using PAR, PKCE is then mandatory, AM responds with an error if it is not used..

Development Postman collection has been updated to support PAR which includes changes to generate and supply PKCE parameters.

Functional tests for this will be done as part of epic: https://github.com/SecureApiGateway/SecureApiGateway/issues/1105
