### ISSUE TITLE
Build support for the publication of statistics into IG config

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#244]
# Description

ASPSPs must report performance and usage statistics to OBIE on a quarterly basis. As the start and the end point of an OB API Request some support for measuring and reporting API performance must be added to IG. 

## Relevant OB Specifications.

This page outlines the ASPSP requirements with regard to publication of statistics;
[https://standards.openbanking.org.uk/operational-guidelines/availability-and-performance/publication-of-statistics/latest/](https://standards.openbanking.org.uk/operational-guidelines/availability-and-performance/publication-of-statistics/latest/)

**Describe the solution you'd like**
We should have IG measure the relevant response times, and publish the data as it occurs to an interface so that the collection of the statistics and the storage/handling of the statistics are not the responsibility of the SBAT. i.e. SBAT will measure (where appropriate) the performance/usage data and report it and the customer will be responsible for storing/processing the data.

### Release Notes

Affected App: X

Description: X
<end release notes>

**Comment by dbadham-fr** [comment]
Implemented by: https://github.com/SecureApiGateway/SecureApiGateway/issues/1151
