### ISSUE TITLE
After sprint planning have technical discussions regarding each issue in the current sprint

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#266]
### Describe the action

Create technical meetings to clarify the solutions proposed on the subtask defined in the sprint planing.
- Go through the solutions together to be sure everything is alright. 
- The OB documentation is confusing and can be interpreted differently by anyone.

### Acceptance criteria (optional)

All team members understand the technical aspects of issues they are working on in the current sprint. 

### Additional Context (optional)

- Technical events

**Comment by BohoCode** [comment]
We have been better at this
