### ISSUE TITLE
Remove AM and IG config from the initializer repository. 

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#303]
The initializer repo should just contain the go code that will deploy config. The config should live in it's own git repository. This way it will be easier for customers to just take the config indeplendently of the initializer. 

Separation of concerns.

**Comment by shaunharrisonFR** [comment]
Change the approach from cloning code in github to try and build the container with the code from another repo in it via github action for building container & dockerfile
