### ISSUE TITLE
Unified monitoring and alerting for obdemo-bank and Identity Cloud

### ISSUE THREAD

**Issue by christian-brindley** [SecureApiGateway/SecureApiGateway#31]
## Story

As a customer I want to monitor the end to end open banking platform so that I have a view of system health and am alerted for any potential or actual service issues.

## Acceptance criteria

- Availability of real time dashboard showing event feeds from the bank deployment and from Identity Cloud
- Alerting on defined events and thresholds

**Comment by BohoCode** [comment]
Insufficient resources to address this.
