### ISSUE TITLE
Create methods with only mandatory fields

### ISSUE THREAD

**Issue by andra-racovita** [SecureApiGateway/SecureApiGateway#352]
### Description

1. Create methods in [securebanking-openbanking-uk-obie-datamodel](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk/tree/master/securebanking-openbanking-uk-obie-datamodel) to initialize objects only with the mandatory fields according to the [Open Banking Read-Write API Profile - v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/read-write-data-api-profile.html) for:

      - [ ] [Account and Transaction API Profile - v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/profiles/account-and-transaction-api-profile.html)
      - [ ] [Domestic Payments Consents - v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-payment-consents.html)
      - [ ] [Domestic Payments - v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-payments.html)
      - [ ] [Domestic Scheduled Payment Consents - v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-scheduled-payment-consents.html)
      - [ ] [Domestic Scheduled Payment - v3.1.8](https://openbankinguk.github.io/read-write-api-site3/v3.1.8/resources-and-data-models/pisp/domestic-scheduled-payments.html)

2. Create functional tests with only the mandatory fields for all the objects reminded earlier.

**Comment by BohoCode** [comment]
Is this still valid???

**Comment by jorgesanchezperez** [comment]
Not valid, has been implemented on each journey subtask.
