### ISSUE TITLE
IG - dynamic OB endpoint discovery - enforce endpoints

### ISSUE THREAD

**Issue by christian-brindley** [SecureApiGateway/SecureApiGateway#40]
## Story

As an ASPSP I want to publish and allow only the OB endpoints which I support.

## Acceptance criteria

- IG provides routes for all OB endpoints supported by the ASPSP
- Endpoints discovered via RS endpoint

## Tasks

- Define RS discovery endpoint
- Base routes on discovered endpoints

**Comment by BohoCode** [comment]
Done
