### ISSUE TITLE
sbat-infra mutating-webhook create build pipeline

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#426]
The mutating-webhook: https://github.com/ForgeCloud/sbat-infra/tree/master/cluster/mutating-webhook contains go code which needs to be built into a docker image.

There is currently no automated way to compile/test the go code and build the docker image.

**Comment by shaunharrisonFR** [comment]
@dbadham-fr this would be a nice one to pick up, so we just want a github action like in others for PR and Merge - pr will compile and test and then the merge will actually build the docker image and push to the registry?

**Comment by dbadham-fr** [comment]
yes, it might need to go into its own git repo in order to achieve that?
