### ISSUE TITLE
Cache and reuse test accountId in functional tests

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#490]
A lot of tests require an accountId in order to query for data relating to a specific account.

There is a common pattern to grab the accountId when setting up a test fixture, example code:
```
val accountId = AccountRS().getFirstAccountId(accountsApiLinks.GetAccounts, accessToken)
```

This is doing a REST API call each time, the resulting accountId is always the same so we should cache it. This will enable us to speed up running many tests by removing a REST call for each test which depends on an accountId.

**Comment by dbadham-fr** [comment]
The code change to achieve this would be rather messy.

A better approach is to review how we manage test data. If the accountId is static and bound to the test user that we are using, then it makes sense to add it to our environment configuration as a static string.

**Comment by BohoCode** [comment]
Is the first account ID the same in every environment? I guess if the test-data initializer is pushing the user's test data into the system then it will be the same right??
