### ISSUE TITLE
Make the process of running the functional tests against different environments easier

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#536]
The target state is to be able to run the functional tests against any sbat environment by passing a cmd line flag

Something like the following:
```
./gradlew tests_v3_1_8 -Penv=dbadham-fr
```

The current setup allows gradle profiles to be defined but this seems to be overkill as it requires a config file per environment, currently the only difference in these files would be the environment variable which is used to build the urls to various endpoints in the environment.

Review the best way to switch the target environment of the functional tests.

**Comment by BohoCode** [comment]
Would be ideal to use an environment variable. This can be set from the pipelines then, or in a docker container, or command line.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/536?planning-poker) with Zenhub @BohoCode @dbadham-fr @mariantiris @shaunharrisonFR

**Comment by dbadham-fr** [comment]
For all CDK environments, all that needs changing in the profile is the environment value: https://github.com/SecureApiGateway/securebanking-openbanking-uk-functional-tests/blob/master/gradle/profiles/profile-default.gradle.kts#L43

For FIDC environments, an additional change is required to set the correct cookie name:
https://github.com/SecureApiGateway/securebanking-openbanking-uk-functional-tests/blob/master/gradle/profiles/profile-default.gradle.kts#L46

`amCookieName` and `cookieName` appear to be duplicates.

**Comment by shaunharrisonFR** [comment]
I've added new profiles for the time being for a quick and easy win, option to explore the env var should be done in future
