### ISSUE TITLE
Identity management empty columns when display intent lists

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#579]
## Description
When navigates to identity management to display the list of any intent some columns in the list are empty.

## To reproduce
- Navigate to https://iam.dev.forgerock.financial/ and sign in.
- In `Native Consoles` navigate to `Identity Management`.
- In `Identity Management` navigate to `MANAGE` and select one intent data to display the list.
- Check that are displayed empty columns.

**Comment by BohoCode** [comment]
This will need to be addressed in time for the demo on the 15th of Nov at the meetup

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/579?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris @shaunharrisonFR

**Comment by mariantiris** [comment]
Investigated the issue and it looks like IDM has some issues when displaying properties from nested objects. The response made by the UI to the managed object API contains all the properties but they are not properly displayed.

This issue should be verified after the upgrade to IDM v7.2 is complete.

**Comment by BohoCode** [comment]
This is still the same with 7.2.0. We should raise and issue with the IDM team.

**Comment by BohoCode** [comment]
We're not going to get around to fixing this are we?
