### ISSUE TITLE
Move complex IG Groovy script logic into Java

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#584]
IG groovy scripts provided a quick way to get functionality working, but the downside is that they cannot be unit tested and it is tricky to reuse code (without writing a java library).

In this epic we would like to identify important Groovy scripts which would be used in a Production deployment of SBAT and move these scripts into Java modules within IG (and write unit tests for them).

**Comment by BohoCode** [comment]
All sub tasks moved to #1114
