### ISSUE TITLE
File Payments - The FileContent field is not viewable

### ISSUE THREAD

**Issue by mariantiris** [SecureApiGateway/SecureApiGateway#596]
### Describe the bug

The FileContent field in the filePaymentIntent object from IDM is not viewable in IDM UI.

### Steps to reproduce the behaviour.

1. Go to postman collection and submit a file payment file
2. Go to IDM UI and look for the patched file content
3. The content of the file cannot be visualized in the UI.

### Expected behaviour

The content should be viewable.

### Current behaviour

The content is not viewable

### Code analysis (optional)

To fix this issue we need to make viewable the FileContent field from the filePaymentsIntent.json file [here](https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-fidc-initializer/blob/master/config/defaults/secure-open-banking/managed-objects/filePaymentsIntent.json)

To be:
          "FileContent": {
            "title": "File content",
            **"viewable": true,**
            "type": "string",
            "description": "File content",
            "isVirtual": false
          }

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/596?planning-poker) with Zenhub @BohoCode @dbadham-fr @mariantiris
