### ISSUE TITLE
DCR review error handling in IG

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#641]
DCR flow has no error handling filter, therefore errors are not handled in a single consistent fashion.

Review how we notify end users that an error has occurred, errors where the client has submitted a bad request object should conform to the spec for DCR: https://www.rfc-editor.org/rfc/rfc7591#section-3.2.2

Review how we log details of errors for customers to debug DCR issues.

There are 2 general classes of error that we need to be mindful of:

- Logic/Validation implemented in IG
- HTTP error responses from upstream systems (AM/IDM)

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureBankingAccessToolkit/SecureBankingAccessToolkit/641?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris

**Comment by dbadham-fr** [comment]
Error responses for DCR should conform with the OAuth2 spec: https://www.rfc-editor.org/rfc/rfc7591#section-3.2.2

If an error response is returned by AM, then it will typically be of this format.

**Comment by dbadham-fr** [comment]
Initial implementation can be seen in PR:
https://github.com/SecureBankingAccessToolkit/securebanking-openbanking-uk-gateway/pull/234

Moving this to review state while I work on the DCR conformance suite, which provides a method of testing some of the changes in the PR

**Comment by dbadham-fr** [comment]
Errors from AM will be passed back to the client, when testing I have verified that AM produces responses compliant with the DCR spec.

IDM errors handling will be reviewed as part of: https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/683 . The existing calls to IDM are a mess, it makes sense to fix these up as we refactor the code.
The IDM errors will generally be server errors 5xx, as the client will have submitted a valid DCR request but we have been unable to create an ApiClient for it.

**Comment by dbadham-fr** [comment]
TO DO - review logging when an AM error occurs.
