### ISSUE TITLE
Configure IG not to log AM UI resources

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#678]
IG is now reverse proxying AM for all external routes.

When a PSU is required to login, as part of consent flow, then the AM UI assets (html, css, js etc) are fetched through IG. 

This results in the assets being logged when they are retrieved from AM (the full GET response is logged), which is causing the logs to become very large.

Example (truncated):
```
--- (request) id:8a00d3a6-7e58-412e-a4b8-c2b55f77fe1f --->

GET https://iam.dbadham-fr.forgerock.financial/am/XUI/css/chunk-vendors.27c211a9.css HTTP/1.1
```
```
<--- (response) id:8a00d3a6-7e58-412e-a4b8-c2b55f77fe1f ---

HTTP/2 200 OK
accept-ranges: bytes
content-length: 86891
content-type: text/css
date: Wed, 16 Nov 2022 08:59:05 GMT
etag: "62b08ceb-1536b"
last-modified: Mon, 20 Jun 2022 15:06:19 GMT
strict-transport-security: max-age=15724800; includeSubDomains

/*!
 * BootstrapVue Custom CSS (https://bootstrap-vue.org)
 */

/*!
 * BootstrapVue Custom CSS (https://bootstrap-vue.org)
 */.bv-no-focus-ring:focus{outline:none}@media (max-width:575.98px){.bv-d-xs-down-none{display:none!important}}@media (max-width:767.98px){.bv-d-sm-down-none{display:none!important}}@media (max-width:991.98px).....................................
```

Review how we do logging for the AM routes which hit the UI and remove logging of UI assets.

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/678?planning-poker) with Zenhub @dbadham-fr

**Comment by dbadham-fr** [comment]
I think we need to create a route which matches access to the UI, then turn off the capture decorator for this route.

``` 
"condition": "${matches(request.uri.path, '^/am/XUI/*')}"
```

**Comment by dbadham-fr** [comment]
The second option from the above comment makes most sense, parking this until https://github.com/SecureApiGateway/SecureApiGateway/issues/676 is done.
