### ISSUE TITLE
Postman: Missing steps for Domestic Scheduled Payment

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#681]
ForgeRock SBAT - TPP Flows (OBIE Certificates) is missing steps to test Domestic Scheduled Payment APIs.

These should be "Step 6" in the collection. Instead we have a duplicate of Step 5:
![image.png](https://images.zenhubusercontent.com/6290a02eb2287c64b6741fed/2ade0503-e5b1-4bb0-b0da-1332ac400d8f)

**Comment by jorgesanchezperez** [comment]
I have deleted the duplicated Domestic Payment tests coverage steps.

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/681?planning-poker) with Zenhub @BohoCode @dbadham-fr @mariantiris
