### ISSUE TITLE
Abstract Transport Certificate validation in routes

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#689]
Currently the routes use the ParseCertificate.groovy script to parse the eidas formatted cert. We then check the roles are suitable for the route being called. i.e. AISP routes must present eidas certificate that has the correct role. 

A better way to do this is to validate the TPP transport certificate with the OB Directory?? 
If we can abstract this mechanism away such that it will be possible to change that functionality to support the use of other types of certificate etc that would be ideal.

## Reasoning behind the change

Roles in the eIDAS style certificates are there as specified by this document: https://www.etsi.org/deliver/etsi_ts/119400_119499/119495/01.06.01_60/ts_119495v010601p.pdf

It states:

> Roles are attributes which can be used to indicate the specific roles that a payment service provider is authorized to
> operate under as by the competent authority.

In the Open Banking ecosystem, this allows a TPP/ASPSP to enrol in Open Banking ecosystem very easily. Rather than OBIE having to do all of the background checks to verify the registration of an organisation with the National Competent Authority (NCA), e.g. the FSA in the UK, they can be assured that the issuer of the eIDAS certificate has done all the necessary checks and the information that is required to be known by the OBIE is carried in the issued eIDAS certificates. 

So, it is the role of the trusted directory owner to ensure that the organisation can't create software statements that have roles that the organisation is not authorized by their NCA to perform. They may do this via a trust process, or they may, as in the case of the OBIE, choose other means to do this, i.e. trusting the data in an organisations issued eIDAS cert. 

When it comes to the API Provider (the ASPSP) enforcing ApiClient role rules on certain routes, then the ApiProvider must trust the trusted directory, and the software statement that are issued by the directory for that ApiClient. So, the SecureApiGateway should not be trusting both the trusted directory and the data in a certificate as this becomes brittle in ecosystems where role information is not in the issued certificates, for example when an ApiProvider chooses to run their own trusted directory and issue their own ApiClient certificates and Software Statements.

**Comment by BohoCode** [comment]
See also #691

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/689?planning-poker) with Zenhub @dbadham-fr

**Comment by dbadham-fr** [comment]
Makes sense to tackle #729 first, as this will provide us with the resources needed to validate the transport certs (namely the JWKS).

**Comment by dbadham-fr** [comment]
I've added logic to the filter to test if the cert is valid by calling method: java.security.cert.X509Certificate#checkValidity() ; this validates the cert's issue and expiration dates vs the current date.

I've attempted to test this with an old OBWac, however it appears that nginx will reject such certs upfront.

**Comment by dbadham-fr** [comment]
Added: `TransportCertValidationFilter`

This validates that the client's MTLS certificate is valid by checking that it exists in their JWKSet (as determined by their ApiClient and TrustedDirectory attributes).

The validation logic is applied by a TransportCertValidator instance, adding DefaultTransportCertValidator implementation which checks for a certificate match by transforming the incoming cert into a JWK and comparing the JWK.x5c value against the values in the JWKSet for the ApiClient.

Adding the filter to FetchApiClientResourcesChain so that the validation is applied to all OB routes.
