### ISSUE TITLE
conformance-dcr tool: automate building docker images

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#693]
1. https://github.com/SecureApiGateway/conformance-dcr
Currently, docker images must be manually built and pushed.
Automate this process via a GitHub action, as per our other repos.

2. Get the tests running in codefresh during the pipeline, may need changing to the pipeline yaml for docker image / tag parameters

3. Move pipelines yaml to sbat-infra

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/693?planning-poker) with Zenhub @shaunharrisonFR

**Comment by shaunharrisonFR** [comment]
Put back into in progress for adding a workflow for when the merge is complete for the image to be built and pushed to the main repo.
Then change the sbat-infra pipeline for DCR to point to the proper repo
