### ISSUE TITLE
Support tls_client_auth method of client authentication

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#694]
Currently we only support `private_key_jwt` client authentication method.

Implement `tls_client_auth` client authentication method. Note, this method is FAPI compliant.

AM needs to be configured for `tls_client_auth` using Public Key Infrastructure (PKI), see AM docs: https://backstage.forgerock.com/docs/am/7.2/oauth2-guide/client-auth-mtls.html#pki-mtls

The key thing that needs to be configured is the truststore containing the certificates for the trusted authories for mTLS. For our current use case this means we need a truststore which contains the Open Banking Test Directory's Issuing and Root certs.

Specs:
https://datatracker.ietf.org/doc/html/rfc8705
https://connect2id.com/products/server/docs/guides/oauth-client-authentication#tls_client_auth
https://openid.net/specs/openid-financial-api-part-2-1_0.html#authorization-server

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/694?planning-poker) with Zenhub @dbadham-fr

**Comment by dbadham-fr** [comment]
The above approach only really works for a CDK deployment, even then it would be a pain to create the keystore and encrypted password within the AM container.

A better approach is to use the [Google Secret Manager secret store](https://backstage.forgerock.com/docs/am/7.2/security-guide/secret-stores.html#google-GSM-secret-stores), this will work with CDK and FIDC. In fact, this is simpler to setup in FIDC!

This store will fetch secrets in PEM format from Google Secrets.

Steps to configure the CDK:

Create a secret contain the CA certs as a PEM string (can be multiple certs in the same file), name `oauth2-ca-certs`

Bind the k8s default service account (per namespace) to the google service account that will access the secret manager, for example: `sbat-master-dev-nodes@sbat-dev.iam.gserviceaccount.com` and annotate the k8s default service account:

```
# bind sbat-master-dev-nodes google service account to dbadham-fr-cdk/default k8 account
gcloud --project sbat-dev iam service-accounts add-iam-policy-binding sbat-master-dev-nodes@sbat-dev.iam.gserviceaccount.com \
--member=serviceAccount:sbat-dev.svc.id.goog[dbadham-fr-cdk/default] \
--role='roles/iam.workloadIdentityUser'

# add annotation to default service account
kubectl annotate serviceaccount default\
--namespace=dbadham-fr-cdk \
iam.gke.io/gcp-service-account=sbat-master-dev-nodes@sbat-dev.iam.gserviceaccount.com
```
**TO DO** Figure out the best way to do the above. When testing locally, it seemed that the above needed to be done prior to the pod being started, I had to delete my am pod in order to get it working.
**TO DO** Decide if this is the best service account to use, whichever account we use we need to ensure that it has role: `roles/secretmanager.secretAccessor`

The remaining steps are configuring AM:

Create the Google Secret Manager secret store, set file type as PEM (the remaining fields should be self explanatory).

Add mapping, secret id: `am.services.oauth2.tls.client.cert.authentication` alias: `oauth2-ca-certs` (matches the google secret name)

The OAuth2 provider settings need to be configured as per the previous comment. These AM steps should be configurable by enhancing the initializer.

**Comment by dbadham-fr** [comment]
Devops tasks for CDK deployment:

1. Review existing Google service account provision done via terraform, does it make sense for the CDK pod to bind to one of these existing accounts? If not, create a new service account via terraform for this purpose
2. Grant the Google service account role: `roles/secretmanager.secretAccessor`
3. Review if we should be using a different k8s service account, currently the cdk does not create one and relies on the default account. In the current setup, this account is used by all pods in the namespace. Should we provision a different k8s service account for the AM pod? Depending on the outcome of this, we may need to make changes to the forgeops deployment to use the new account.
4. Bind the k8s service account to the google service account
5. Annotate the k8s service account with `iam.gke.io/gcp-service-account`

**Comment by dbadham-fr** [comment]
See https://github.com/SecureApiGateway/securebanking-openbanking-uk-fidc-initializer/pull/143 for details on the intializer changes to support `tls_client_auth`, namely the ability to configure Google Secret Stores via initializer config yaml.

The issue is now on hold until the devops changes are implemented.

**Comment by dbadham-fr** [comment]
Interestingly, we had an issue this morning where private_key_jwt authentication requests were attempting to call out to Google Secrets to validate the client cert.

Further investigation is needed to figure out why this is. Perhaps it is to do with binding the cert to the access token, as we have the client cert header configured now then perhaps AM is using this method to bind the cert. Previously, we relied on passing the cnf_key param.

**Comment by dbadham-fr** [comment]
Tested this manually using Postman.

Raised: https://github.com/SecureApiGateway/SecureApiGateway/issues/739 to cover testing via the DCR conformance suite.
