### ISSUE TITLE
Support subject_type public for DCR

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#697]
https://github.com/SecureApiGateway/SecureApiGateway/issues/623 removed support for public subject_type.

There is no mention in the OB or FAPI specs that public should not be supported.

Therefore we should re-enable public subject type and test if the FAPI conformance test "happy path" works with clients registered with public.

**Comment by BohoCode** [comment]
Not going to support public for v1.0

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/697?planning-poker) with Zenhub @dbadham-fr

**Comment by dbadham-fr** [comment]
Added this back into the OAuth2 config, both public and pairwise clients are able to complete the FAPI happy path testing.
