### ISSUE TITLE
Support certificate bound access tokens

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#698]
This is a requirement of FAPI advanced spec:
https://openid.net/specs/openid-financial-api-part-2-1_0.html#authorization-server

> shall only issue sender-constrained access tokens;
shall support MTLS as mechanism for constraining the legitimate senders of access tokens;

AM docs: https://backstage.forgerock.com/docs/am/7.2/oidc1-guide/oauth2-dynamic-client-registration.html

After further investigation, see comments, cert bound access tokens are supported by using the `cnf_key` param.

In this issue we would like to test proof of possession.

Tasks:

- [x] Investigate how proof of possession has been implemented in SBAT 
- [x] Investigate if FAPI suite has any tests to check proof of possession
- [x]  Test proof of possesion manually
- [x]  Investigate refresh token flow

**Comment by dbadham-fr** [comment]
We currently do not support `tls_client_auth` auth method.
It makes sense to tackle: https://github.com/SecureApiGateway/SecureApiGateway/issues/694 first and then add the necessary enhancements to enable the cert bound access tokens.

As mentioned previously, thought needs to be given to how the access tokens will be restricted if the `private_key_jwt` auth method is being used.

**Comment by dbadham-fr** [comment]
After further investigation, it appears we do support certificate bound access tokens by setting the `cnf_key` url param when hitting the access token endpoint.

See groovy script: AddCnfKey

See documentation: https://backstage.forgerock.com/docs/am/7.2/oauth2-guide/oauth2-PoP-Cert.html

There may be no work needed here, we may need to use the 2 different methods depending on the auth method being used.

**Comment by dbadham-fr** [comment]
From the above comment, it looks like no work is needed to implement this functionality.

Tasks:

- [ ] Investigate if FAPI suite has any tests to check proof of possession
- [ ] Test proof of possesion manually
- [ ] Investigate refresh token flow, the refresh token doesn't include a claim binding it to the cert. It is assumed that access tokens obtained by refreshing will be bound to the original cert but need to test this

**Comment by BohoCode** [comment]
Think about how brittle this solution is with regards to client certificate rolling/refreshing. Is there a way we can bind something like a hash of the subject DN rather than the full certificate thumbprint. What is a certificate thumbprint based on? Will the thumbprints change when a new cert is issued???

**Comment by BohoCode** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/698?planning-poker) with Zenhub @dbadham-fr

**Comment by dbadham-fr** [comment]
`fapi1-advanced-final` test case (the happy path), has a step: `Try Client1's MTLS client certificate with Client2's access token`

This is testing the proof of possession.

**Comment by dbadham-fr** [comment]
It makes sense to park this work until the tls_client_auth token_endpoint_auth method is supported https://github.com/secureapigateway/secureapigateway/issues/694

There was an interesting observation when attempting to get the above to work, see comment:
https://github.com/SecureApiGateway/SecureApiGateway/issues/694#issuecomment-1344085723

Once we have that method working then we can test if we can consistently achieve cert bound access tokens using the `ssl-client-auth` header (even for private_key_jwt). If this is done using the cert DN then this should allow access tokens to remain usable even after the cert has been rolled.

If that is possible then the cnf_key logic may be able to be removed.

**Comment by dbadham-fr** [comment]
The filter to add the cnf_key can now be removed, as we supply the cert via a header to AM then AM is able to calc the hash itself and embed it into the access token.

**Comment by dbadham-fr** [comment]
AM has implemented cert bound access tokens using the hash method.

Quote from [AM Docs](https://backstage.forgerock.com/docs/am/7.2/oauth2-guide/oauth2-PoP-Cert.html):
> Clients can authenticate to the OAuth 2.0 endpoints by presenting X.509 self-signed or CA-signed certificates as per version 12 of the [OAuth 2.0 Mutual TLS Client Authentication and Certificate Bound Access Tokens](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-mtls-12) internet-draft.

The implication of this is:

> Moreover, this implies that access tokens are invalidated when clients update their certificates.

Therefore, there is no benefit of using `private_key_jwt` or `tls_client_auth` wrt cert bound access tokens. When the cert is updated the existing tokens will be invalidated.

**Comment by dbadham-fr** [comment]
A separate issue has been raised to create automated tests for this, see https://github.com/SecureApiGateway/SecureApiGateway/issues/763
