### ISSUE TITLE
RCS-Backend refactor to deserialise with jackson ob objects consents stored in IDM

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#700]
## Description
Currently the implementation on RCS backend to build the consent details to be displayed in RCS-UI decode the json-based object retrieved from IDM using the Gson library parsing the json string.

We need a good refactor on the RSC backend, to stop using Gson directly and start using Jackson for idm consent objects, until now idm objects have not been typed, but now we have the proper type for serialising and deserialise the OB. object requests, but for now it's an old legacy implementation, the client platform retrieves the json-based object from IDM to pass it to the RCS backend as a json-based string format.

>The current implementation logic needs to be designed again to implement the correct patterns to manage properly the objects obtained from IDM and at the same time have a typification with no duplications per version.

**Comment by BohoCode** [comment]
Maybe don't look at this until #566 is being addressed.

**Comment by dbadham-fr** [comment]
No longer needed, as IDM consent store has been replaced.

IDM decoders can be removed as part of: https://github.com/SecureApiGateway/SecureApiGateway/issues/1082
