### ISSUE TITLE
Allow AM pod deployed by CDK to access secrets stored in Google Secrets Manager

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#703]
AM needs to be able to source secrets stored in Google Secrets Manager in order to support tls_client_auth OAuth2 authentication method. The public certs of the CAs that will be trusted by AM need to be stored in a secret.

Following this approach, rather than using a Keystore file in the AM pod, enables us to configure AM for tls_client_auth consistently across CDK and FIDC deployments.

Devops tasks for CDK deployment:

1. Review existing Google service account provisioning done via terraform, does it make sense for the CDK pod to bind to one of these existing accounts? If not, create a new service account via terraform for this purpose
2. Grant the Google service account role: `roles/secretmanager.secretAccessor`
3. Review if we should be using a different k8s service account, currently the cdk does not create one and relies on the default account. In the current setup, this account is used by all pods in the namespace. Should we provision a different k8s service account for the AM pod? Depending on the outcome of this, we may need to make changes to the forgeops deployment to use the new account.
4. Bind the k8s service account to the google service account
5. Annotate the k8s service account with `iam.gke.io/gcp-service-account`
6. Create the secret in Google Secret Manager that contains the OB Directory CA cert chain as a pem

_Originally posted by @dbadham-fr in https://github.com/SecureApiGateway/SecureApiGateway/issues/694#issuecomment-1342279226_

**Comment by shaunharrisonFR** [comment]
As part of this ticket, a new GCP and Kubernetes service account, instead of granting full read permissions to all the secrets, a condition has been applied so that it only applies to the value within the am-secret-name variable. For us this is called am-oauth2-ca-certs
