### ISSUE TITLE
Create Nightly Code build for all components

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#705]
Create nightly builds which build and test all the individual code projects.

This is very useful for catching issues caused by dependencies that are changing e.g. SNAPSHOT dependencies in Java. For example: if module A depends on module B version 0.0.1-SNAPSHOT, then if this version of B is changed in a breaking fashion, then we will only realise when A is rebuilt (which is currently only when it is worked on). This means that the feedback loop for breakages is slow.

The regular build process won't pickup such issues as module B will build successfully, it is something in its public API that has changed and causes a breakage in module A.

Using nightly builds we can catch such issues much quicker (they should be fairly rare). As we are forcing everything to be rebuilt each night, which will pickup any changes to the SNAPSHOT dependencies.

In the future we can enhance the nightly builds to also carry out tasks which do vulnerability scanning and other tasks which would take too long to do on a per PR/merge build basis.

For now the nightly build should compile and test the code (it should produce no binaries or docker images).

**Comment by shaunharrisonFR** [comment]
@dbadham-fr may need to discuss this ticket with you when you get time

**Comment by shaunharrisonFR** [comment]
Start with `Core` & `OB`
