### ISSUE TITLE
Investigate GitHub actions building PRs from forked repos

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#707]
We've had our first PR from a fork!

Unfortunately it seems that our GitHub actions aren't working.

Example PR:
https://github.com/SecureApiGateway/securebanking-openbanking-uk-fidc-initializer/pull/146

Failure message
```
Run google-github-actions/auth@v0
Error: google-github-actions/auth failed with: retry function failed after 1 attempt: the GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"! If you are specifying input values via GitHub secrets, ensure the secret is being injected into the environment. By default, secrets are not passed to workflows triggered from forks, including Dependabot.
```

Fork our own repo somewhere and test out the workload, we need to be able to build and test PRs submitted by the community.

**Comment by dbadham-fr** [comment]
Looks like the `pull_request_target` event can be used to solve this issue:
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks

**Comment by dbadham-fr** [comment]
Additionally, we need to review the codefresh deployment trigger that currently runs as part of the pr action. This will fail if it is run by a user without an environment.

I don't think there is any sensible deployment we can do here, so it is best to skip this step for fork PRs. Testing will need to be done by syncing a particular environment manually.

**Comment by shaunharrisonFR** [comment]
so by default, github blocks access to secrets when the repo is forked, if we do want to proceed with actions from forked repositories we'll need to add our secrets to something else and decrypt at build time, but obviously ensure that no one will be able to access them by modifying the yaml files

**Comment by shaunharrisonFR** [comment]
https://github.com/SecureApiGateway/securebanking-openbanking-uk-gateway/actions/runs/3930931066/jobs/6721536773

Example of a run where a new PR fork workflow has ran and access to secrets granted
