### ISSUE TITLE
Postman: Domestic scheduled Payment tests coverage missed

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#713]
Postman collection `ForgeRock SBAT - TTP Flows (OBIE Certificates)` have  the `Domestic payment` tests coverage duplicated and doesn't have the proper test coverage for `Domestic scheduled payment`

**Comment by jorgesanchezperez** [comment]
Duplicated: https://github.com/secureapigateway/secureapigateway/issues/681

**Comment by BohoCode** [comment]
@jorgesanchezperez This issue isn't estimated and isn't in a sprint?

**Comment by BohoCode** [comment]
Ah, closed duplicate! Don't worry!
