### ISSUE TITLE
/backoffice/payment-funds-confirmation/{accountId} - header `x-fapi-financial-id` should be optional

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#715]
The header `x-fapi-financial-id` is defined as mandatory for /backoffice/payment-funds-confirmation/{accountId} so that when the request doesn't set the `x-fapi-financial-id` the call fails because IG doesn't creates that mandatory header when isn't supplied in the request.

```json
{
    "Code": "400",
    "Id": "4d4069462449af01fea952899d309397",
    "Message": "[Status: 400 Bad Request]",
    "Errors": {
        "ErrorCode": "UK.OBIE.Header.Missing",
        "Message": "Missing request header 'x-fapi-financial-id' for method parameter of type String"
    }
}
```
We need:
- [x] Disable the mandatory header in postman
- [ ] Disable the mandatory header in functional tests

**Comment by BohoCode** [comment]
See also https://github.com/secureapigateway/secureapigateway/issues/484

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/715?planning-poker) with Zenhub @BohoCode @dbadham-fr @mariantiris
