### ISSUE TITLE
Test iam-initializer running against a clean FIDC environment

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#719]
Issue #304 managed to fix up the FIDC tenant used by the nightly environment. This environment already existed and needed many objects to be manually deleted to force re-creation by the initializer.

In this issue we would like to test the initializer can configure a fresh FIDC environment.

To achieve this we either need to provision a new environment or ask if the cloud team can do a factory reset on our current environment (not sure if such a feature exists).

**Comment by BohoCode** [comment]
We have done this and everything worked out OK
