### ISSUE TITLE
Create filters and filter chains to obtain items used commonly in routes

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#729]
Create filters that@

- Obtain the TrustedDirectory by issuer
- Obtain the ApiClient by client_id 
- Obtain the JWKS public key from the TrustedDirectory using the kid

These filters are needed in most OB routes. 

These filters will simplify work currently in progress: 
#691
#689

**Comment by dbadham-fr** [comment]
FetchApiClientFilter has been created to fetch the ApiClient data from IDM.

New data class: com.forgerock.sapi.gateway.dcr.ApiClient has been added, into which the IDM response will be decoded.

Other filters will then be able to retrieve the ApiClient java object from the AttributesContext (available as the attributes variable in groovy scripts) by using the `apiClient` key.

Note: AttributesContext was used in preference to creating a new context type (ApiClientContext etc), as it provides greater flexibility. The ApiClient, via the AttributesContext, will then be available to all subsequent filters on the request and response paths.
Whereas a new context type would only be available to subsequent filters on the request path.

**Comment by dbadham-fr** [comment]
We now have `FetchApiClientFilter` and `FetchTrustedDirectoryFilter`, these have been combined into a chain of filters which can be installed into particular routes, see definition from config.json:

```
{
      "name": "FetchApiClientAndTrustedDirectoryDataChain",
      "type": "ChainOfFilters",
      "comment": "This filter chain will set the apiClient and trustedDirectory attributes in the context based on the client_id of the request",
      "config" : {
        "filters": [
          {
            "comment": "Add ApiClient data to the context attributes",
            "name": "FetchApiClientFilter",
            "type": "FetchApiClientFilter",
            "config": {
              "idmGetApiClientBaseUri": "&{urls.idmGetApiClientBaseUri}",
              "clientHandler": "IDMClientHandler"
            }
          },
          {
            "comment": "Add TrustedDirectory configuration to the context attributes",
            "name": "FetchTrustedDirectoryFilter",
            "type": "FetchTrustedDirectoryFilter",
            "config": {
              "trustedDirectoryService": "TrustedDirectoriesService"
            }
          }
        ]
      }
    }
```

This chain must be installed after `OAuth2ResourceServerFilter`, as we need to ensure that the access_token provided is valid before looking up these resources.

Filters after `FetchApiClientAndTrustedDirectoryDataChain` can access the apiClient and trustedDirectory via the `AttributesContext`.

The attribute key to use to fetch the data is available via a const in the filter java code, see: https://github.com/SecureApiGateway/securebanking-openbanking-uk-gateway/blob/master/secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/FetchApiClientFilter.java#L58

There is also a helper method which can be used to fetch the data from the context in Java: https://github.com/SecureApiGateway/securebanking-openbanking-uk-gateway/blob/master/secure-api-gateway-ig-extensions/src/main/java/com/forgerock/sapi/gateway/dcr/FetchApiClientFilter.java#L97

In groovy filters, the attributes context is exposed via the `attributes` binding, therefore accessing the apiClient is done via: `attributes.apiClient`.
