### ISSUE TITLE
Allow only Sweeping VRPType

### ISSUE THREAD

**Issue by mariantiris** [SecureApiGateway/SecureApiGateway#736]
### Components

IG

### Describe the issue

Currently we are only supporting Sweeping Domestic VRPs.

We should add a check in IG to make sure we allow consents to be created only if VRPType is "UK.OBIE.VRPType.Sweeping". For the other VRP types return an error.

### Acceptance criteria (optional)

- [x] When the consent not is a Sweeping is rejected with the proper error description
- [x] It have the proper coverage test

### Code solution approach (optional)

- [x] Create check validation in the route to reject the consent

**Comment by jorgesanchezperez** [comment]
The script fails for `GET` requests because the body is null, to fix it:
- Introduce a condition to check the VRP type only when is a `POST` requests otherwise pass thru the next handler
