### ISSUE TITLE
Review, rationalize and document RS/RCS configuration items (spring config)

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#749]

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/749?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez @shaunharrisonFR

**Comment by dbadham-fr** [comment]
I've had a play with moving the config from spring config server into the RS, it seems fairly straightforward: https://github.com/SecureApiGateway/securebanking-openbanking-uk-rs/pull/132

I think we should tackle this as part of this issue.

**Comment by dbadham-fr** [comment]
Spring config for both apps has been greatly simplified.

Most of the config in the application.yml serves as sensible defaults, customers are able to override these properties in the normal spring way, see: https://docs.spring.io/spring-boot/docs/2.1.9.RELEASE/reference/html/boot-features-external-config.html#boot-features-external-config-profile-specific-properties.

Mandatory config has been documented in commented out block within application.yml; the recommended way to supply this config is by using OS environment variables.

Customers are able to get a deployment running with the minimal config by following the documentation below:
- https://github.com/SecureApiGateway/SecureApiGateway/wiki/Remote-consent-service-(RCS)
- https://github.com/SecureApiGateway/SecureApiGateway/wiki/Resource-server-(RS)
