### ISSUE TITLE
Run initializer using Service Account

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#754]
FIDC now supports Service Accounts, which can be used to get an access token that is scoped to perform REST API calls.

See docs:
https://backstage.forgerock.com/docs/idcloud/latest/release-notes/rapid-channel/service-accounts.html
https://backstage.forgerock.com/docs/idcloud/latest/release-notes/rapid-channel/service-accounts-authenticate-to-rest-api-with-access-token.html

Tasks:
- [ ] Review if it is possible to set up a service account in the CDK so that we have a consistent approach to using the REST API.
- [ ] Use service account authentication for FIDC
- [ ] Support access token authentication in REST API calls (this will either replace the current cookie based auth OR be in addition to it, depending on whether the CDK can support access tokens)

**Comment by dbadham-fr** [comment]
Need to discuss this with @BohoCode .

This issue was raised prior to discovering the CS_config_manager, if we don't intend to use the initializer in a customer deployment then there is less of a priority to use a service account.
#786

**Comment by shaunharrisonFR** [comment]
Don't think this is needed anymore, as the initializer at this time is only used in devenv

**Comment by dbadham-fr** [comment]
This is now a necessity for running the initializer against the nightly environment, as 2FA will be required from 1st March 2024. See: https://backstage.forgerock.com/docs/idcloud/latest/product-information/migration-dependent-features/tenant-administrator-mandatory-2-step-verification-faq.html

**Comment by shaunharrisonFR** [comment]
Going to implement for Test User as it creates the PSU user

**Comment by shaunharrisonFR** [comment]
Work has been merged for test data, waiting for tomorrow to see results of running from new

**Comment by shaunharrisonFR** [comment]
Outcome of all this was

CDK does not support service accounts so most of the proposed work isn't possible

We decided to use service accounts for the test initialiser as communication to the cloud instance is required when the cloud type is FIDC

We are not setting this up for FIDC initialiser  as we no longer run the service against our cloud tenants, and use the fr_config_manager instead
