### ISSUE TITLE
Get instance of identity cloud for new release-version's deployment

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#761]
This will be needed when deploying as part of #748

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/761?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez @shaunharrisonFR

**Comment by shaunharrisonFR** [comment]
From Richard.D

We can provision an instance , which we won't have to pay for, via a [cumulus front end tool](https://cumulus.forgerock.com/#/sign-in) 

Conf guide [here](https://wikis.forgerock.org/confluence/display/SA/Cumulus)

**Comment by shaunharrisonFR** [comment]
New instance has been provisioned 

https://openam-sapig-relenvs.forgeblocks.com/login/?realm=/#/

May need a going over to see if anything is required
