### ISSUE TITLE
Replace use of deprecated external-secrets-manager

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#766]
[external-secrets-manager ](https://artifacthub.io/packages/helm/external-secrets/kubernetes-external-secrets)has been deprecated. Currently, it is installed via helm here: [cluster-initialise.yml#L82](https://github.com/ForgeCloud/sbat-infra/blob/ed1cf81c3b4653527a85c9797a292a71d2c95b43/pipeline/template/cluster-initialise.yml#L82)

The replacement is External Secrets Operator (ESO): https://github.com/external-secrets/external-secrets

**Comment by dbadham-fr** [comment]
Review: https://github.com/SecureApiGateway/SecureApiGateway/issues/764#issuecomment-1400284291

Review if ESO can work with binary secrets out of the box, without us having to base64 encode the secret prior to upload.

**Comment by BohoCode** [comment]
Not done in Dev

**Comment by shaunharrisonFR** [comment]
@dbadham-fr from your comment above, I had to remove isBinary: true from the secrets template. The secrets still got created successfully but unsure on the base64 part of it
