### ISSUE TITLE
Run IG containers as non-root user

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#776]
IG containers that we deploy are all running as root, it is a docker best practice to run as a non-root user.

Other FR products, such as AM deployed by CDK, run as forgerock user.

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/776?planning-poker) with Zenhub @shaunharrisonFR @jorgesanchezperez @dbadham-fr

**Comment by dbadham-fr** [comment]
The IG base image is using the `forgerock` user to run the application. 

Fixing our docker image by using the `forgerock` user.
