### ISSUE TITLE
Create automated tests using IG hosted Trusted Directory certificates

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#778]
We have developed a Test Trusted Directory which is hosted by IG, currently to test this issuer we need to use the `ForgeRock SBAT - TPP Flows (Test Certificates) collection manually.

This Test Trusted Directory is something that clients are keen to use in development, therefore we need to ensure that it is working.

The tests can also be run to verify that the Test Trusted Directory has been configured & deployed properly.

**Comment by dbadham-fr** [comment]
I think it is sufficient to test the DCR flow for this issuer, therefore the it may make sense to adapt / extend https://github.com/SecureApiGateway/conformance-dcr . The tests in this repo test the DCR process and then verify that a client_credentials access token can be retrieved using the registration. This should cover everything that is specific to the Test Trusted Directory.

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/778?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez

**Comment by dbadham-fr** [comment]
New functional test framework has tests for the core deployment, some of which use the IG hosted test Trusted Directory.

https://github.com/SecureApiGateway/secure-api-gateway-functional-test-framework
