### ISSUE TITLE
Fix RCS to sign consent decision JWTs sent to AM

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#779]
RCS is currently using a route hosted by IG to sign the RCS consent decision JWTs. This route in IG needs to be removed for security reasons, any component that needs to sign a message should do so itself.

Design work:

- [x] Review which key RCS should be using for this purpose
- [x] Review whether AM Remote Consent should use a jwks_uri or an embedded jwks containing the RCS key info (current impl is the latter)

Implementation tasks:

- [ ] Implement JWT signing logic in RCS
- [ ] Create RSA key for signing and store in google secrets
- [ ] Mount signing private key into RCS docker image and add configuration to use this key
- [ ] Write unit and integration tests for signing
- [ ] Configure AM to use the new RCS signing key; continue to configure an embedded JWKS
- [ ] Remove IG route: 70-ob-jwkms-rcs-signresponse.json

**Comment by dbadham-fr** [comment]
This issue was observed when documenting how to configure the Test Directory. As part of this we wanted to consolidate the keys into a single keystore, and also document and test the process of generating such a keystore.
When IG was configured to use this keystore then the RCS flow started to break, as we need to update the JWKS configured in AM for Remote Consent.

**Comment by dbadham-fr** [comment]
It is unclear why the RCS is not able to configure its own secret signing key and configure AM to trust this.

**Comment by BohoCode** [comment]
For now we will do this the quick way. i.e. create a new signing key and add it to google secrets and modify rcs charts to use that signing. RCS needs to do the signing. 
Ensure AM trusts the signing key.

**Comment by BohoCode** [comment]
Create a trust mechanism for internal component commuication

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/779?planning-poker) with Zenhub @jorgesanchezperez @dbadham-fr @shaunharrisonFR

**Comment by dbadham-fr** [comment]
Commands used to generate RSA private and public keys:
```
openssl genrsa -out rcs.key 2048
openssl rsa -in rcs.key -outform PEM -pubout -out rcs.pem
```

The private key: rcs.key will need to be loaded as a secret by rcs container.

The public key: rcs.pem will need to be transformed into a JWKSet and configured in AM.
