### ISSUE TITLE
Create ASPSP software statement in Open Banking Directory for SAPI-G

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#781]
SAPI-G does not currently have an Open Banking Directory ASPSP Software Statement, it also does not have an OB signed OBWac or OBSeal.

- Create a new ASPSP software statement in Open Banking Directory
- Create new OBWac and OBSeal and associate them with the new software statement
  - Store the keys in the ob-ci-secrets repo

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/781?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez @shaunharrisonFR

**Comment by dbadham-fr** [comment]
Software Statement:
Secure API Gateway Test Bank v1
https://manager.openbankingtest.org.uk/participants/PSD2/0015800001041REAAY/software-statements/YfxeCuxENNVSwUiJbS0LIH

Domain: v1.ob-sandbox.forgerock.financial
