### ISSUE TITLE
Create Ingress for Open Banking MTLS

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#782]
Connections to Open Banking APIs are supposed to be protected by an OB Directory signed OBWac, and use MTLS.

Calls to the AS (AM), need to be MTLS or TLS on a per end point basis. All PSU browser interactions should use the non-MTLS end point so that the end user does not have to provide a client cert (they won't have one) and doesn't have to configure their browser to trust the OB CA cert (it won't by default).

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/782?planning-poker) with Zenhub @dbadham-fr @shaunharrisonFR @jorgesanchezperez

**Comment by dbadham-fr** [comment]
https://github.com/SecureApiGateway/SecureApiGateway/issues/781 has created an SSA and certs for the release environment.

These do not work for dev.

If we want to use an OB cert for dev then we would need to create certs containing all of the developer env DNS entries, as our currently DNS hierarchy is not wildcardable.

Nginx will only permit a single wildcard at the top level. This is NOT valid `obdemo.*.forgerock.financial` neither is `*.*.forgerock.financial` and `*.forgerock.financial` is valid but doesn't match.

Alternatively we would need to structure our environments so that the env is the top level domain e.g. `dev.obdemo.forgerock.financial` `dbadham-fr.obdemo.forgerock.financial`. obdemo is kind of meaningless so could be replaced by devenv or something,.

**Comment by dbadham-fr** [comment]
For dev it may be overkill to use an OB Wac, instead we could continue as we currently do and only supply the OB Wac for the release env.

This would require us to be able to have different ingress config for dev vs release env.

**Comment by dbadham-fr** [comment]
Creating new ingress `open-banking` in addition to the `forgerock` and `ig-web` (dev only access to IG Studi UI) ingresses.

As Ingress tls configure is done on a per ingress basis then we need to split out the open banking routes from everything else.

This new ingress can then be configured to use an OBWac.

For now the ingress has been split out but continues to use the Let's Encrypt cert until we can figure out a strategy for dev.
For the customer release env, we can use the OBWac created in #781

Additional changes:
- forgerock ingress has mTLS configuration removed
- open-banking ingress has mTLS configuration
- forgerock ingress has new rule to match `/am/XUI` so that AM simulates a Bank login UI, which would be protected by the Bank's regular TLS cert

**Comment by dbadham-fr** [comment]
The PR above will not do what we need when we switch to using OBWac and Let's Encrypt cert.

The nginx ingress controller collates all of the Ingress definitions for a particular host to produce a single config block in the nginx.conf within the container. So in our example above, the forgerock, open-banking and ig-web ingresses get combined into a single config block.

Here's an example configuration block for my namespace (individual rule contents have been redacted and a number of rules deleted)

```
server {
		server_name obdemo.dbadham-fr.forgerock.financial ;
		
		listen 80  ;
		listen 443  ssl http2 ;
		
		set $proxy_upstream_name "-";
		
		ssl_certificate_by_lua_block {
			certificate.call()
		}
		
		# Client cert configuration (MTLS)
		# PEM sha: 7a238b1dd1bdf209593b13aa68cd3725a55095f7
		ssl_client_certificate                  /etc/ingress-controller/ssl/ca-dbadham-fr-obri-ca.pem;
		ssl_verify_client                       optional_no_ca;
		ssl_verify_depth                        1;
		
		# Ingress rules - truncated for brevity
		location ~* "^/ig(/|$)(.*)" {}
		
		location ~* "^/jwksproxy/" {}
		
		location ~* "^/jwksproxy" {}
		
		location ~* "^/rcs/api/" {}
			
		location ~* "^/rs/" {}
		
		location ~* "^/" {}
		
	}
```

This means that only a single tls secret can be used for all Ingresses defined for the same host. The `ssl_certificate_by_lua_block` is doing the heavy lifting and resolving the cert to use.

I've played around with this in my environment and if I set different certs for the same host, then only one of the certs actually gets used.

**Comment by dbadham-fr** [comment]
Parking this until we get our ingress design right.
