### ISSUE TITLE
Add in CODEFRESH_PROJECT variable

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureApiGateway/SecureApiGateway#785]
As we have created a secure-api-gateway-release project to separate release and dev pipelines, this has caused our existing pipeline to fail for where create calls the initialise pipeline as sbat-infra is hard coded

This will need applying to most of the pipelines as the deployment.yaml pipeline calls the various pipelines

NOTE: While doing this, the project sbat-infra might as well be changed to secure-api-gateway-dev & possibly a secure-api-gateway-devops

**Comment by BohoCode** [comment]
Done
