### ISSUE TITLE
Use CS_config_manager in release pipelines to configure FIdC

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#786]
To create our v1.0.0 release we need to use cs_config_manager to pull config from our FIdC instance and then put the resulting config under source control as part of v1.0.0

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/786?planning-poker) with Zenhub @dbadham-fr @shaunharrisonFR

**Comment by BohoCode** [comment]
This is now done for v1
See https://wikis.forgerock.org/confluence/display/SBAT/FIDC+Config+Management for the details of how this is done
