### ISSUE TITLE
Kubernetes External Secrets Deprecated

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureApiGateway/SecureApiGateway#803]
The repo we use for external secrets has been [deprecated](https://github.com/external-secrets/kubernetes-external-secrets)

Suggested in the repo to move to [ESO](https://github.com/external-secrets/external-secrets)

Will need to see what changes (if any) would be required and what version to go with

**Comment by BohoCode** [comment]
This is fixed now. Got done as part of the build the relenvs issue..
