### ISSUE TITLE
Version deployment config release for Helm charts

### ISSUE THREAD

**Issue by jsanhc** [SecureApiGateway/SecureApiGateway#814]
You can version the helm charts themselves. We will need to do this for the individual applications. Ideally we'd have a pipeline in github which only runs if the files in the infra folder changes, and the result would be that the chart version is incremented. This would ideally be automated but perhaps for now for V1, the github action would simply alert the team that a change has been made and to manually increment the value

These values are then used in the umbrella chart to say what version of the applications should be used in v1 | v2 and so on

So v1 will use 

RS: V1.0.1
RCS: V1.3.0
UI: V1.2.3

V2 will use

RS: V2.0.0
RCS: V2.3.1
UI: V2.0.5

And so on. I beleive the idea is for this to be manual, we want to ensure we are setting the correct values for the umbrella version

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/814?planning-poker) with Zenhub @dbadham-fr @shaunharrisonFR
