### ISSUE TITLE
X-fapi-financial-id header should be optional starting with v3.1.2

### ISSUE THREAD

**Issue by frlaura-jianu** [SecureApiGateway/SecureApiGateway#817]
The `x-fapi-financial-id` header has to be removed from all APIs and Controllers in RS as it is no longer required starting with v3.1.2 according to https://openbankinguk.github.io/knowledge-base-pub/standards/read-write.html#what-error-code-should-an-aspsp-send-back-to-a-tpp-if-a-wrong-x-fapi-financial-id-was-sent-in-the-request.

**Comment by BohoCode** [comment]
Remove all use of this header across all versions. Later we will remove access to any versions prior to 3.1.4 where signing headers changed. b64 etc...
