### ISSUE TITLE
Build config.json for IG for the production deployment to relenvs

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#826]

**Comment by dbadham-fr** [comment]
Review prod config, PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/336 has disabled the Test Trusted Directory. This configuration is hardcoded, for dev we use an environment variable to control it.

Review if there's a use case for running the test trusted directory with IG in production mode
