### ISSUE TITLE
Review which repos should be private 

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#841]
We should only expose necessary repositories to customers. Any repos that exist to support our internal development environments etc should be made private - this will necessitate moving them to a paid ForgeRock owned github organisation. 

Any repos that are no longer used should be deleted.

**Comment by shaunharrisonFR** [comment]
After going through v1.0.0 yesterday and seeing what repos we work with, I think this can be closed off? @BohoCode
