### ISSUE TITLE
Prevent non-mtls ingress being used to access resources in AM which require mtls

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#844]
The forgerock (non-mtls) ingress can be used to access AM, there are currently too many AM routes to configure on the ingress so it has a catch all /am rule. There is nothing stopping someone from adjusting the mtls URLs returned by the .well-known and using this ingress to access the token endpoint.

We need to prevent access to the resources which require mtls from using the forgerock ingress.

Note: This is not a problem for RS as all routes must use mtls and therefore, no ingress rules are defined on the forgerock ingress for RS.

**Comment by dbadham-fr** [comment]
The /register endpoint is enforcing the MTLS in the IG route, so will reject requests without a cert or with an invalid cert.

The /accecss_token endpoint is not enforcing MTLS at the moment, if we fix bug: https://github.com/SecureApiGateway/SecureApiGateway/issues/852 then nothing needs to be done in this issue.

Alternatively, we need to add routes which forward the ingress traffic to a default backend (which always responds 404) or we need custom nginx config to do a deny.

**Comment by dbadham-fr** [comment]
Priority is to fix #831 

If this is fixed then the client will get an error in both cases saying that their client cert needs to be supplied.

**Comment by BohoCode** [comment]
Based on Dan's comments this is not a security issue and the MTLS check is done in all AM MTLS routes, so if a hacker tries to access using the non mtls route they will get an error.
