### ISSUE TITLE
Use Forgeops 7.2.0 for IG

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureApiGateway/SecureApiGateway#860]
We're in the process of moving to using forgeops base files for deploying IG and various components associated with IG, we'll want to use 7.2.0 once we know we have moved over okay

https://github.com/ForgeRock/forgeops/tree/release/7.2.0/kustomize/base/ig

**Comment by BohoCode** [comment]
Opening as we still don't use the IG 7.2.0 image as a base in our Dockerfile.
