### ISSUE TITLE
Cleanup IG scripts and extensions module to remove manual logging of x-fapi-interaction-id

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#866]
#671 implemented logged the x-fapi-interaction-id by adding it to the MDC. Now all logs with the same context will automatically log the interaction id.

Cleanup the code to remove manual logging of this information

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/866?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez
