### ISSUE TITLE
Payment Funds Confirmation Self Link invalid

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#874]
The Links.Self URL in the funds confirmation response is invalid; the path contains `backoffice` which is an internal implementation detail

Example funds confirmation response:

```
{
    "Data": {
        "FundsAvailableResult": {
            "FundsAvailableDateTime": "2023-03-06T14:17:21+00:00",
            "FundsAvailable": true
        },
        "SupplementaryData": null
    },
    "Links": {
        "Self": "https://mtls.sapig.dbadham-fr.forgerock.financial/backoffice/rs/open-banking/v3.1.10/pisp/domestic-payments-consent/01233243245676/funds-confirmation",
        "First": null,
        "Prev": null,
        "Next": null,
        "Last": null
    },
    "Meta": {
        "TotalPages": null,
        "FirstAvailableDateTime": null,
        "LastAvailableDateTime": null
    }
}
```

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/874?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris

**Comment by dbadham-fr** [comment]
Looks like all Links are broken.

Create payment / Get payment is missing the `rs` path element:
```
{
    "Data": { omitted },
    "Links": {
        "Self": "https://mtls.sapig.dbadham-fr.forgerock.financial/open-banking/v3.1.10/pisp/domestic-payments/PDC_a1ade13d-c36d-4774-91c5-a1794640faad",
        "First": null,
        "Prev": null,
        "Next": null,
        "Last": null
    },
    "Meta": {
        "TotalPages": null,
        "FirstAvailableDateTime": null,
        "LastAvailableDateTime": null
    }
}
```

Accounts data access (contains multiple broken links):
```
{
    "Data": { omitted },
    "Links": {
        "Self": "http://localhost:8080/open-banking/v3.1.10/aisp/balances,https:/sapig.dbadham-fr.forgerock.financial/rs/open-banking/v3.1.10/aisp/balances",
        "First": null,
        "Prev": null,
        "Next": null,
        "Last": null
    },
    "Meta": {
        "TotalPages": 1,
        "FirstAvailableDateTime": null,
        "LastAvailableDateTime": null
    }
}
```

**Comment by dbadham-fr** [comment]
Accounts API issue is due to the `x-ob-url` header from IG being set incorrectly.

The junk localhost url in the example was being sent by Postman, IG was then forwarding it. This has been fixed by removing any `x-ob-url` header sent by the client.

IG was setting the wrong value for the header, it has been fixed by using the mtls domain.

**Comment by dbadham-fr** [comment]
Raised a separate issue to review the best way to construct self links going forwards.

https://github.com/SecureApiGateway/SecureApiGateway/issues/887
