### ISSUE TITLE
API client name seems to be wrong when is registered

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#883]
## Description
The value of client name displayed in the UI, just in the consent page title when the consent is displayed seems to be wrong.

The `api client name` is added in the details consent as `client name` to be displayed in the consent UI but the current value stored in the api client as name is the api client id (this data value is duplicated in different api client fields).
**consent details object**
```java
details.setClientName(apiClient.getName());
```
**Expected value**
```json
"clientName": "Automating-testing",
```
**Current value**
```json
"clientName": "ebSqTNqmQXFYz6VtWGXZAa",
```
When a client is request a CDR flow we need to store in api client name the correct value of the client name instead of the client id provided in the SSA.

**SSA registration**
```json
"software_id": "ebSqTNqmQXFYz6VtWGXZAa",
  "software_client_id": "ebSqTNqmQXFYz6VtWGXZAa",
  "software_client_name": "Automating-testing",
  "software_client_description": "TPP used for automating testing",
```

**Comment by dbadham-fr** [comment]
This bug was introduced by PR: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/314

**Comment by jorgesanchezperez** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/883?planning-poker) with Zenhub @BohoCode @dbadham-fr @frlaura-jianu @mariantiris
