### ISSUE TITLE
Remove RS user test data from default application.yml spring config

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#884]
The application.yml config file contains a block of test account data, this data is deployment specific and should not be included by default. See: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/blob/ab92fca12bdc5a41030206671240201546bf6f9e/secure-api-gateway-ob-uk-rs-server/src/main/resources/application.yml#L39-L49

This data should be supplied via helm values on a per deployment basis.

**Comment by dbadham-fr** [comment]
As the data may be complex, it is better to use a config file for this purpose.

Investigate having an optional block of config in the helm values file that gets inserted into an RS configmap, the yaml can be embedded within a single key that can then be mounted in the docker container.

The config can be mounted under /app/config/application.yml , this will then be resolved as Spring Configuration Outside of the Jar.

**Comment by BohoCode** [comment]
Removed - now in the config map
