### ISSUE TITLE
Use ESV variables and configuration placeholders in FIDC config

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#892]
https://backstage.forgerock.com/docs/idcloud/latest/tenants/configuration-placeholders.html

The aim of this issue is to produce FIDC configuration templates for SAPI-G

By using configuration placeholders we can make SAPI-G config generic, allowing it to be deployed to any tenant.

- [x] Update the nightly environment configuration to use placeholders and ESVs
- [ ] Document ESVs
- [ ] Deploy config to release environment for v1

**Comment by BohoCode** [comment]
Create a tool to push cluster specific ESVs to a FIdC instance

This is necessary because the cs_config_manager doesn't currently push ESVs. So before we can push config to a deployment we need the ESVs to be created in that deployment's FIdC.
