### ISSUE TITLE
Migrate service_account.* users to proper Service Accounts

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#899]
The initializer is creating the following regular users:
- service_account.ig

These users are being used to simulate Service Accounts. 

Migrate these users to proper Service Accounts.

**Comment by dbadham-fr** [comment]
https://backstage.forgerock.com/docs/idcloud/latest/tenants/service-accounts.html

To Do, need to see if these are supported in CDK environment. As we need a solution that works for all environments.

**Comment by BohoCode** [comment]
CDK doesn't do service accounts.
