### ISSUE TITLE
Create a tool to push cluster specific ESVs to a FIdC instance

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#903]
## Create a tool to push cluster specific ESVs to a FIdC instance

This is necessary because the cs_config_manager doesn't currently push ESVs. So before we can push config to a deployment we need the ESVs to be created in that deployment's FIdC.

_Originally posted by @BohoCode in https://github.com/SecureApiGateway/SecureApiGateway/issues/892#issuecomment-1479394740_

**Comment by dbadham-fr** [comment]
A helper script to get an ID Cloud access token has been added to the deployer.
https://github.com/ForgeCloud/secure-api-gateway-relenv-deployer/pull/10

Parking working on a tool to create the ESVs in favour of higher priority tasks for v1.

**Comment by dbadham-fr** [comment]
cs_config_manager supports pushing secrets and variables by using OS environment variables.

Now testing if the tool can do what we need.

**Comment by dbadham-fr** [comment]
Closing this issue in favour of using cs_config_manager.

See documentation: https://wikis.forgerock.org/confluence/display/SBAT/FIDC+Config+Management
