### ISSUE TITLE
Create a pipeline to build and push gcloud-tools image

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#913]
Source: https://github.com/ForgeCloud/sbat-infra/tree/master/pipeline/containers/gcloud-tools

Repo Image: https://console.cloud.google.com/gcr/images/sbat-gcr-develop/eu/ci/gcloud-tools?tag=latest

This image needs to be built by a pipeline and versioned.

**Comment by shaunharrisonFR** [comment]
Work on this is now complete

This work extended to the letsencrypt and mutating-webhook containers as well as the gcloud-cli container. 

It will only increase the minor version so going from 1.0.1 -> 1.0.2

Latest is still being tagged, as all our pipelines use latest at this time, but we now have versioning for if we need to go back a version for whatever reason
