### ISSUE TITLE
PR workflow check integrity isn't trigger when the PR is created from release workflow

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#914]
## Description
Currently when the release caller workflow finish, the last job is create the release PR for the next development iteration, we expect trigger the PR workflow to check the PR integrity but isn't triggered.

> Pull requests created by the action using the default GITHUB_TOKEN cannot trigger other workflows. If you have `on: pull_request` or `on: push` workflows acting as checks on pull requests, they will not run.
> 
> When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run. This prevents you from accidentally creating recursive workflow runs. For example, if a workflow run pushes code using the repository's GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur.

## Workaround
- Pull the release branch  (`release/x.y.z`)  linked in the release PR and push an empty commit to trigger the PR workflow to check the PR integrity.
- Add the reviewers
- Request the review PR

## Tasks
- [ ] Follow the documentation to implement a fix https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow

**Comment by shaunharrisonFR** [comment]
Do we need this? When we create a release we are only creating a new branch of what is currently in master and then changing some of the values to the next iteration, which shouldn't really cause the check PR workflow to fail. All checks would have already ran when doing the merges from branch to master and master should always be in a working state.
