### ISSUE TITLE
Review and cleanup nginx configuration

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#918]
Warnings from nginx-controller logs:
```
nginx: [warn] the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /etc/nginx/nginx.conf:154

nginx: [warn] the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/nginx.conf:153

"nginx: [warn] the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /etc/nginx/nginx.conf:152"
```

Review that our nginx configuration including ingress annotations.

When we are using annotations on a per ingress basis, review if it is more suitable to use a configmap configuration instead (if one exists) to apply the settings to all ingresses.

**Comment by shaunharrisonFR** [comment]
As far as I can see, we aren't setting any of those configurations ourselves, we are however using helm chart 4.2.0 for nginx and it's now up to 4.7.0 - may be worth us looking at updating to a newer version in dev and seeing if the errors go

**Comment by shaunharrisonFR** [comment]
4.7.0 is still showing these errors - there is a 4.8.0 released last week, will give this a week longer and then try it
