### ISSUE TITLE
Review FAPI Test warning for fapi1-advanced-final-discovery-end-point-verification

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#920]
FAPI Test: `fapi1-advanced-final-discovery-end-point-verification`

Warning: `CheckJwksUriIsHostedOnOpenBankingDirectory: JWKS URI is not hosted on the OpenBanking Directory. This is acceptable on a sandbox, but production systems must use an OpenBanking Directory hosted JWKS.`

Values
actual: `sapig.ob-sandbox-v1.forgerock.financial`
expected: `keystore.openbanking.org.uk`

We are hosting the JWKS URI in AM, instead it needs to be hosted by the OpenBanking Directory (or OpenBanking Test Directory)

**Comment by BohoCode** [comment]
Duplicate of #968
