### ISSUE TITLE
Automate Consent UI testing

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#921]
Recent issues: https://github.com/SecureApiGateway/SecureApiGateway/issues/915 , https://github.com/SecureApiGateway/SecureApiGateway/issues/924 highlighted a gap in our testing for the consent UI.

Currently we rely on manual testing.

Investigate using a tool to automate testing the Consent UI.

**Comment by BohoCode** [comment]
This is a big job. We would need to use Functional Test to set up the system (DCR, create consent etc) then selenium to test the UIs...

**Comment by BohoCode** [comment]
No UI engineer on the project and this would require picking up selinium or something. Insufficient resources to make this happen
