### ISSUE TITLE
Improve RCS tests to validate the consent details response

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#926]
**Decision to re-visit this after UI re-write**

This issue has a similar goal to https://github.com/SecureApiGateway/SecureApiGateway/issues/921 , we would like to improve the quality of the RCS and get better at capturing functional regressions.

Recent issues: https://github.com/SecureApiGateway/SecureApiGateway/issues/915 , https://github.com/SecureApiGateway/SecureApiGateway/issues/924 have both been caused by a change in the data being returned by the RCS ConsentDetailsApiController, this was due to some refactoring done in the RCS. The issue is only spotted when using the UI.

We need to add some integration tests which validate the response of the ConsentDetailsApiController for each IntentType. These tests should be doing a deep equals on the response object to ensure that all of the required data is there.

**Comment by BohoCode** [comment]
We may be able to take the cypres test from OBRI and use them to test our UIs.

Long discussion about seperating concerns of RCS into consent store (generic) and specific (e.g. OB UI)



![IMG_2856](https://github.com/SecureApiGateway/SecureApiGateway/assets/1516395/81fd8af4-bb79-4e2c-999c-80e5f8e1f4cd)

**Comment by BohoCode** [comment]
To test this contract now we would need to call selenium FROM the functional tests as we need to get the system into the right state to populate the UI... i.e. where a constent has been created etc. 

This is a big chunk of work, and considering teh UI needs re-writing we should look at testability of the UI, when we are aproaching that work.

**Comment by BohoCode** [comment]
This isn't going to happen....
