### ISSUE TITLE
Deploy v1.0.0 of Secure API Gateway to ob-sandbox-v1

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#927]
Steps needed to do this;

- [ ] Release deployment repositories (if required) - add wiki process page

###  Release v1.0.0 of all SAPI-G release artificats 
see #812 
[Release process checklist](https://wikis.forgerock.org/confluence/display/SBAT/Release+process)

**release `1.0.0`**

**Run manually `create-release` workflow in the following repositories**
- [x] **1**: Release [secure-api-gateway-parent](https://github.com/SecureApiGateway/secure-api-gateway-parent)
  - [x]  Run release workflow
  - [x] Checkout release branch and add an empty commit and push so that checks run on the PR with the release commits in 
  - [x] Merge release PR
- [x] **2**: Release [secure-api-gateway-ob-uk-common](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-common)
  - [x] Create PR to update parent version
  - [x] Run release workflow
  - [x] Checkout release branch and push empty commit to make checks on PR run
  - [x] Merge release PR
- [x] **3**: [IG secure-api-gateway-ob-uk](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk)
   - [x] Run release workflow
   - [x] Checkout release branch
   - [x] Push commit to make checks on PR run
   - [x] Merge release PR
- [x] **3**: [secure-api-gateway-ob-uk-rs](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs)
  - [x] Create PR to update 
    - parent and bom versions
    - helm chart versions
  - [x] Run release workflow
  - [x] Checkout release branch
  - [x] Push commit to make checks on PR run
  - [x] Merge release PR
- [x] **3**: [secure-api-gateway-ob-uk-rcs](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs)
  - [x] Create PR to update parent and bom versions
  - [x] Run release workflow
  - [x] Checkout release branch
  - [x] Push commit to make checks on PR run
  - [x] Merge release PR
- [x] **3**: [secure-api-gateway-ob-uk-ui](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-ui)
    - [x] Create PR to update rcs-ui package.json and package-lock.json with the new release version
       - run: Specific version: npm version ${version-number} --no-git-tag-version ex. npm version 0.9.1 --no-git-tag-version
       - Or Next version: npm version patch --no-git-tag-version  
   - [x] Run release workflow
   - [x] Checkout release branch
   - [x] Push commit to make checks on PR run
- [x] **3**: [secure-api-gateway-ob-uk-test-data-initializer](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-test-data-initializer)
    - [x] Create PR to update chart version
    - [x] Run release workflow
    - [x] Publish release draft if necessary
- [x] **3**: [secure-api-gateway-ob-uk-functional-tests](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-functional-tests)
  - [x] Update version field to release value and update version of secure-api-gateway-ob-uk-commons-bom used in build.gradle.kts
  - [x] Run create release workflow
- [x] **3**: [fr-platform-config](https://github.com/SecureApiGateway/fr-platform-config)
    - [x] Run release workflow
- [x] **3**: [conformance-dcr](https://github.com/SecureApiGateway/conformance-dcr)
    - [x] Run release workflow
- [ ] **3**: [secure-api-gateway-releases](https://github.com/SecureApiGateway/secure-api-gateway-releases)
  - [x] Create PR to update Charts.yaml parent and child versions to newest
  - [x] Run workflow release
  - [ ] Delete release branch

- [ ] **3**: [secure-api-gateway-releases-helpers](https://github.com/SecureApiGateway/secure-api-gateway-releases-helpers)
  - [x] Create PR to update Charts.yaml parent version if there has been a change since the last version
  - [x] Run workflow release 
  - [ ] Update release with release notes
  - [ ] Set release to released
  - [x] Delete release branch

**Create manually a release Tag `v1.0.0`**
- [x] **1**: [secure-api-gateway-relenv-deployments](https://github.com/ForgeCloud/secure-api-gateway-relenv-deployments)
  - [x] Update .env, .pipelineenv & values.yaml variables to the newest version - ensure package_version matches the newest version to install
  - [x] Update kustomization.yaml to update the repo version to the correct version
  - [x] Create Tag  
- [x] **1**: [secure-api-gateway-relenv-deployer](https://github.com/ForgeCloud/secure-api-gateway-relenv-deployer)
- [x] **1**: [sbat-infra](https://github.com/ForgeCloud/sbat-infra)

## Then deploy
- [x] Deploy v1.0.0 - See <deployment process wiki page>
- [x] Make functional tests pass
- [x] Check correct certs are in place
  - [x] https://sapig.ob-sandbox-v1.forgerock.financial/am/
  - [x] https://sapig.ob-sandbox-v1.forgerock.financial/rcs/api/
  - [x] https://sapig.ob-sandbox-v1.forgerock.financial/rcs/ui/
  - [x] https://sapig.ob-sandbox-v1.forgerock.financial/jwksproxy
  - [x] https://mtls.sapig.ob-sandbox-v1.forgerock.financial/am/oauth2/realms/root/realms/alpha/access_token
  - [x] https://mtls.sapig.ob-sandbox-v1.forgerock.financial/am/oauth2/realms/root/realms/alpha/register
  - [x] https://mtls.sapig.ob-sandbox-v1.forgerock.financial/rs/
  - [x] https://sapig.ob-sandbox-v1.forgerock.financial/jwkms/
- [x] Make DCR tests pass
- [ ] Create postman collection and environment 
- [ ] Ensure hybrid flow/consent UIs work for accounts, payments etc
- [ ] Make FAPI Conformance suite tests pass
- [ ] Create Secure API Gateway v1.0.0 exists and works and is published

**Comment by shaunharrisonFR** [comment]
PR For Secure-API-Gateway-Release update

https://github.com/SecureApiGateway/secure-api-gateway-releases/pull/18

**Comment by jorgesanchezperez** [comment]
Running release workflow for ui
https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-ui/actions/runs/4619218660

**Comment by jorgesanchezperez** [comment]
Running workflow for fr-platform-config
https://github.com/SecureApiGateway/fr-platform-config/actions/runs/4619237628

**Comment by jorgesanchezperez** [comment]
Running workflow for conformance-dcr
https://github.com/SecureApiGateway/conformance-dcr/actions/runs/4619241475

**Comment by jorgesanchezperez** [comment]
Running workflow for Ig gateway
https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/actions/runs/4619320413

**Comment by shaunharrisonFR** [comment]
Running release workflow for secure-api-gateway-helpers

https://github.com/SecureApiGateway/secure-api-gateway-releases-helpers/actions/runs/4619224644

**Comment by jorgesanchezperez** [comment]
Running workflow for test data initialiser
https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-test-data-initializer/actions/runs/4619538659

**Comment by jorgesanchezperez** [comment]
Running release workflow for RCS
https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rcs/actions/runs/4619665570

**Comment by shaunharrisonFR** [comment]
Running release workflow for secure-api-gateway-release
https://github.com/SecureApiGateway/secure-api-gateway-releases/actions/runs/4619750234

**Comment by shaunharrisonFR** [comment]
Create deploy pipelines for ob-sandbox-v1

https://g.codefresh.io/pipelines/edit/new/builds?id=63e6148c74bf4b7630e7cca5&pipeline=devops-create-pipelines&projects=ForgeCloud%2Fsecure-api-gateway-release&projectId=63d3f10000817d1143958f87&context=github-bot

**Comment by shaunharrisonFR** [comment]
Deploy secure-api-gateway-helpers Charts for ob-sandbox-v1

https://g.codefresh.io/build/642d8c04c919a8d302ef108e

**Comment by shaunharrisonFR** [comment]
Deploy secure-api-gateway Charts for ob-sandbox-v1

https://g.codefresh.io/build/642d8cbea6cc8d641eb924d7

**Comment by shaunharrisonFR** [comment]
Run Functional Checks against ob-sandbox-v1

https://g.codefresh.io/build/642d8d842e16a0b7e7356be4

**Comment by shaunharrisonFR** [comment]
Run Conformance DCR against ob-sandbox-v1

https://g.codefresh.io/build/642d90bf21585c2f39ea508f

**Comment by shaunharrisonFR** [comment]
Run Conformance DCR against ob-sandbox-v1

https://g.codefresh.io/build/642d90bf21585c2f39ea508f

**Comment by BohoCode** [comment]
We have an issue with the hybrid/consent flows in this release! 

![image](https://user-images.githubusercontent.com/1516395/230140412-2dc3e882-e2eb-44fe-b4e3-3f3bb98bbd41.png)

[downloaded-logs-20230405-171228.zip](https://github.com/SecureApiGateway/SecureApiGateway/files/11160873/downloaded-logs-20230405-171228.zip)

**Comment by shaunharrisonFR** [comment]
After creating 0.9.1, we failed to run the postman collections against ob-sandbox-v1, this was only done after releasing 1.0.0 and issues were identified, going forward we'll want to include the postman collections in the release checklist before we create a new release

To establish our processes, we are going to close this issue, and open a [new issue](https://github.com/SecureApiGateway/SecureApiGateway/issues/935) and work against a 1.0.1 release

**Comment by shaunharrisonFR** [comment]
Fixes for the issues found are

https://github.com/SecureApiGateway/SecureApiGateway/issues/933
