### ISSUE TITLE
Conformace-dcr Unit tests fails and in consequence the workflows PR and Merge sbat-master fail also

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#928]
Currently, unit tests fail and the PR and Merge sbat-master workflows when they run `make test` fail also.
At the moment `make test` has been disabled from workflows to avoid blocking release tasks until unit tests have been fixed.

- https://github.com/SecureApiGateway/conformance-dcr

**Comment by dbadham-fr** [comment]
Test failures were introduced in PR: https://github.com/SecureApiGateway/conformance-dcr/pull/29

In this change we need to update the unit tests as required by the functional change in the above PR.

I've raised a separate issue to improve the CI process to prevent PRs being merged if the unit tests are failing, see #988

**Comment by jsanhc** [comment]
Fixed in #988
