### ISSUE TITLE
Release RCS-UI CLI and RCS_UI Common and shared components

### ISSUE THREAD

**Issue by jsanhc** [SecureApiGateway/SecureApiGateway#930]
## Description
Currently we provide a release workflow to release the RCS-UI service, that service contains an Angular app that depends on the CLI and common UI shared components.

The CLI and common UI shared components currently are publishing manually each time that we generated a new version with new changes.

Provide a workflow to release the CLI and common UI shared components.

## Tasks
- [ ] Create a workflow to release CLI and common UI shared components

> To consider: the RCS-UI dependencies needs to be updated before build the release to bump the CLI release and common UI shared components release.

**Comment by BohoCode** [comment]
Never going to happen unless we get a UI engineer.
