### ISSUE TITLE
Update secret 'credentials_json' in FIDC initialiazer workflows

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#937]
The secret GCR_KEY has been deprecated and will be deleted in the future.
Update the deprecated **GCR_KEY** in `pr.yml` and `merge.yml` and `release.yml` files to use the new **GCR_CREDENTIALS_JSON**

**Comment by BohoCode** [comment]
@jorgesanchezperez is this done? 
No PRs refering to this issue?
