### ISSUE TITLE
Check, review and restrict the editable managed objects fields in IDM: `userEditable` fields

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#949]
## Description
The user could edit the consent and change manually the values stored in the consent in IDM.

Restrict the editable fields to protect the consent values stored in IDM we need to review the fields defined in the managed objects to identify the fields which may not be edited by the user in the self user UI.

**Comment by BohoCode** [comment]
Consents now managed by the RCS
