### ISSUE TITLE
Avoid overwrite the debtor Account when is provided by the TPP in the consent request

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#954]
## Description
If a TPP when initiates a payment and submit a payment consent provides the optional object `debtorAccount`, the consent are stored in IDM with all values provided by the TPP including all fields values and objects, in that case the `debtorAccount` stored with the consent are the values provided by the TPP.

a) When the TPP provides in the consent the `debtorAccount`:
- The RS validates that the debtorAccount identifiers match with an account stored in RS, it means that the debtorAccount is a valid account, otherwise the consent submitted by the TPP will be rejected with an error.

- When the consent is displayed in the RCS-UI to be approved by the `psu`, the consent is displayed with the user account retrieved from RS that match with the `debtorAccount` account identifiers provided by the TPP in the consent that has been stored in IDM, to display additional data of  `debtorAccount` in RCS-UI.
Only one account is displayed in RCS-UI in that case.

When the `psu` accepts the consent, the consent decision is submitted to RS and RS patch the consent with the account data provided in the submission, overwriting the `debtorAccount` provided by the TPP in the initiation payment consent, and therefore, modifying the original `debtorAccount` data of the consent previously stored in IDM.

The `debtorAccount` must be have the values provided by the TPP in the consent and must not be overwrite.

b) When the TPP does not provides in the consent the `debtorAccount`:
The consent is displayed in the RCS-UI to be approved by the `psu`, the RCS-UI display the list of user accounts retrieved from RS.
The `psu` must select an account, accepts and authorise the consent from RCS-UI, the values of the selected account will be submitted to RS and RS patch the `debtorAccount` in the consent with the account data selected by the `psu`.
In that case any data is overwrite because the TPP have not provided the `debtorAccount` in the consent, and the debtor account is necessary to make the payment.

## Solution suggested
Store the account provided in the consent decision submitted from RCS-UI to RS in an object outside of the `OBIntentObject` stored in the intent in IDM, instead of to be stored in the `debtorAccount` object inside of the consent, so that the `debtorAccount` data submitted by the TPP will never be altered or overwrited.

Reuse the `AccountId` defined in the managed payment objects.

Then when the TPP will request for the consent details the consent will be returned with the same data that the consent was submitted, except these data calculated by the simulation bank internally such as `Charges`

**Comment by jorgesanchezperez** [comment]
Fixed in https://github.com/secureapigateway/secureapigateway/issues/947

**Comment by BohoCode** [comment]
What was the actual bug here @jorgesanchezperez? You have provided a good description of what is happening technically, but what would the problem be for the ApiClient?
