### ISSUE TITLE
Idempotency payment submission fails and creates a duplicated payment

### ISSUE THREAD

**Issue by jorgesanchezperez** [SecureApiGateway/SecureApiGateway#958]
## Description
> This apply to all payments excepts `VRP payments`

When a TPP submit a existing payment the API request must be idempotent, it means that the TPP making multiple identical requests (payment submissions) must get the same response every time.

Currently the process to check if the request is idempotent fails.

We store the payment submission in mongo as json structure where the payment submission object is represented with a field:
- `standingOrder`, `scheduledPayment`, `payment` or `filePayment`

All payment API controllers call [IdempotentRepositoryAdapter#idempotentSave](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/blob/f0f2d3af346c4aa80120b057ccec8e7f23c47775/secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/api/obie/payment/v3_1_5/domesticpayments/DomesticPaymentsApiController.java#L149) that implements the idempotency behaviour to return the existing payment or create one when doesn't exist a payment for the consent and the idempotency key.

- The [IdempotentRepositoryAdapter](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/blob/master/secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/persistence/repository/IdempotentRepositoryAdapter.java) logic uses the repository interface [PaymentSubmissionRepository](https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/blob/master/secure-api-gateway-ob-uk-rs-server/src/main/java/com/forgerock/sapi/gateway/ob/uk/rs/server/persistence/repository/payments/PaymentSubmissionRepository.java) to request the consent by consentId:
```java
@Query("{'payment.data.consentId' : ?0}")
Optional<T> findByConsentId(@Param("consentId") String consentId);
```
That method to find the consent by consentId defines the query to perform the search in mongo db database, but only works if the object store match with the structure `payment.data.consentId`, it means that for the other cases where the field to filter by consentId is `standingOrder.data.consentId`, `scheduledPayment.data.consentId` or `filePayment.data.consentId` always will return an empty optional because never will find any consent by consentId, so that the payment submitted is always created as a duplicated if the TPP submit the same payment multiple times.

**Comment by dbadham-fr** [comment]
The idempotency mechanism needs a redesign to work with the new RCS Consent Store.

The old impl only worked because of a bug in the policy script, which meant that a payment could be submitted for a consent with consumed status.

This bug has been fixed in the new impl, the payment validators check that the consent is in authorised state.

Idempotency checks needs to be done as early as possible, the more biz logic that gets executed the more chance of there being an issue due to there being state changes.

**Comment by dbadham-fr** [comment]
#1090 is blocking this issue, when testing idempotency for payments that contain dates (such as scheduled payments) then we were always hitting the IDEMPOTENCY_KEY_REQUEST_BODY_CHANGED error as the TZ of the object received from the REST API differed to the TZ of the object returned from the database.
