### ISSUE TITLE
Upgrade forgeops to 7.3.0 in development environments

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#963]
Upgrade forgeops version to 7.3.0

Also upgrade the IG docker image to 7.3.0 (currently we use 7.1.0 and forgeops 7.2.0, these should be aligned).

Upgrading IG will allow us to complete our migration to java 17, as IG is the only container running jdk11 at the moment. This should fix an issue we have been having when generating Java Keystores containing secrets for IG, if the jdk version used to create the store is too new then you get runtime errors.

Example error in IG:
```
java.io.IOException: Integrity check failed: java.security.NoSuchAlgorithmException: Algorithm HmacPBESHA256 not available
```

**Comment by shaunharrisonFR** [comment]
https://github.com/ForgeRock/forgeops - look at branches release\ and there isn't a fixed 7.3.0

_manifest for gcr.io/forgerock-io/ig:7.3.0 not found: manifest unknown: Failed to fetch "7.3.0" from request "/v2/forgerock-io/ig/manifests/7.3.0"._


It doesnt look like they have officially released 7.3.0 yet, once it is this can be worked on

Ignore all of this, the naming convention has changed

**Comment by shaunharrisonFR** [comment]
Work for this has been done for Forgeops upgrade & IG to go hand in hand

We are waiting for the release to go through before merging

**Comment by shaunharrisonFR** [comment]
Forgeops is complete, as part of this ticket we tried upping IG to 7.3.0 also, but this hasn't worked successfully - creating ticket #1154  to do this in future
