### ISSUE TITLE
When OBIE fix SSA format, remove validation of SSA from IG and re-enable SSA validation in AM.

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#97]
When OBIE fix SSA format, remove validation of SSA from IG and re-enable SSA validation in AM.

This is to reverse this workaroud for the bad OB Test Directory SSA format

_Originally posted by @BohoCode in https://github.com/SecureBankingAccessToolkit/SecureBankingAccessToolkit/issues/96#issuecomment-951901166_

**Comment by dbadham-fr** [comment]
In June 2022 TDA members voted in favour of Decision 247: to change the datatype definition of the  software statement attribute software_version from decimal to string. This attribute also appears in the software statement assertion (SSA). This attribute's data type will also have to be changed in any relevant data stores. This will be a breaking change.

The change will align this attribute with the standards document that covers Software Statements for OAuth2 Dynamic Client Registrations, i.e. RFC7591. This standard defines the software_version attribute's data type as string. This release will require downtime on the following dates:

**Directory Sandbox 07th February 10:00 – 14:00 GMT**

**Comment by BohoCode** [comment]
SSA is now passed to AM for validation. We are still doing full validation in the DCR route however, as we need to validate the SSA before we can trust the jwks_uri in the SSA and use it to validate the registration request jwt signature.
