### ISSUE TITLE
Add Postman support for JARM

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#974]
Construct authorize requests with response_type="code" and response_mode="jwt"

Add support for using JARM with PAR.

**Comment by BohoCode** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-625027a2231bd8001f38d79f/issues/SecureApiGateway/SecureApiGateway/974?planning-poker) with Zenhub @dbadham-fr @jorgesanchezperez
