### ISSUE TITLE
No buttons visible on the International payment consent UI

### ISSUE THREAD

**Issue by BohoCode** [SecureApiGateway/SecureApiGateway#980]
Version: 1.0.1
Fixed In: 

## Description
When performing the hybrid flow to give consent to an International Payment the dialog does not show any buttons, so I can't approve or reject the consent. 

## Steps to Recreate
1. Perform DCR
2. Create an Internation Payment Consent
3. Perform the hybrid flow to give consent
### Expected Result
The UI shows buttons to allow the user to either give their consent or reject the consent.
### Actual Result
No buttons are shown

![image.png](https://images.zenhubusercontent.com/625028aae7c8d332288ac5d1/52c5f439-12bc-4eda-9fb2-76205ddfcf9f)

**Comment by BohoCode** [comment]
Browser console shows;

`ROR TypeError: Cannot read properties of undefined (reading 'exchangeRate')`

**Comment by dbadham-fr** [comment]
The issue appears to be related to the consent field: `ExchangeRateInformation`, this field is optional in the spec but if when we omit it then we hit the UI issue.

A similar issue also occurs for the International Schedule payment, however in this case the whole UI fails to load and instead just displays a blank page.

International Standing Orders do not appear to be impacted as there is no `ExchangeRateInformation` field in the consent.

Example International Payment Consent which trigger the issue:
```
{
   "Data":{
      "ReadRefundAccount":"No",
      "Initiation":{
         "InstructionIdentification":"ANSM020",
         "EndToEndIdentification":"FRESCO.21302.GFX.01",
         "LocalInstrument":"UK.OBIE.BACS",
         "InstructionPriority":"Normal",
         "Purpose":"CDCD",
         "ExtendedPurpose":"Extended purpose",
         "ChargeBearer":"Shared",
         "CurrencyOfTransfer":"GBP",
         "DestinationCountryCode":"GB",
         "InstructedAmount":{
            "Amount":"10.01",
            "Currency":"GBP"
         },
         "Creditor":{
            "Name":"Creditor Name",
            "PostalAddress":{
               "AddressType":"Residential",
               "Department":null,
               "SubDepartment":null,
               "StreetName":"The Mall",
               "BuildingNumber":"1",
               "PostCode":"WC1 1AB",
               "TownName":"London",
               "CountrySubDivision":null,
               "Country":"UK",
               "AddressLine":null
            }
         },
         "CreditorAgent":{
            "SchemeName":"UK.OBIE.SortCodeAccountNumber",
            "Identification":"40400411270111",
            "Name":"Creditor Agent Name",
            "PostalAddress":{
               "AddressType":"Residential",
               "Department":null,
               "SubDepartment":null,
               "StreetName":"The Mall",
               "BuildingNumber":"1",
               "PostCode":"WC1 1AB",
               "TownName":"London",
               "CountrySubDivision":null,
               "Country":"UK",
               "AddressLine":null
            }
         },
         "CreditorAccount":{
            "SchemeName":"UK.OBIE.SortCodeAccountNumber",
            "Identification":"08080021325698",
            "Name":"Mr Tim Burgess",
            "SecondaryIdentification":"11"
         },
         "RemittanceInformation":{
            "Unstructured":"Internal ops code 5120103",
            "Reference":"FRESCO-037"
         },
         "SupplementaryData":{
            
         }
      },
      "Authorisation":{
         "AuthorisationType":"Any",
         "CompletionDateTime":"2022-07-05T11:47:11+03:00"
      },
      "SCASupportData":{
         "RequestedSCAExemptionType":"BillPayment",
         "AppliedAuthenticationApproach":"CA",
         "ReferencePaymentOrderId":"b19b8b34-26e3-4434-b1a8-736cda5af4a6"
      }
   },
   "Risk":{
      "PaymentContextCode":"Other",
      "MerchantCategoryCode":"mct1",
      "MerchantCustomerIdentification":"merchantId123",
      "DeliveryAddress":{
         "AddressLine":[
            "60 Queens Sq"
         ],
         "StreetName":"Queen Square",
         "BuildingNumber":"60",
         "PostCode":"BS1 1AA",
         "TownName":"Bristol",
         "CountrySubDivision":"en",
         "Country":"GB"
      }
   }
}
```

**Comment by dbadham-fr** [comment]
The issue has been triggered by this change: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/172/files#diff-53d3fdd973560451f12b84fb3e94ec7b1171c944391fc5dc72e9960ef2a5c748R76-R94

**Comment by dbadham-fr** [comment]
Discussed the above with @BohoCode 

In the case where the TPP does not specify the ExchangeRateInformation, then the ASPSP will generate an indicative exchange rate data to show in the UI.

This is similar to the logic that we had prior to this change: https://github.com/SecureApiGateway/secure-api-gateway-ob-uk-rs/pull/172/files#diff-53d3fdd973560451f12b84fb3e94ec7b1171c944391fc5dc72e9960ef2a5c748R76-R94 -- the issue with the original logic was that it was editing the consent request initiation object to add the ExchangeRateInformation; this caused an issue when validating that the consent and payment initiations matched as the TPP would not be providing the ExchangeRateInformation in the payment request (and rightly so).
