### ISSUE TITLE
conformance-dcr run unit tests as part of CI pipeline

### ISSUE THREAD

**Issue by dbadham-fr** [SecureApiGateway/SecureApiGateway#988]
An issue has been raised regarding unit tests being broken on the `sbat-master` branch.

https://github.com/SecureApiGateway/SecureApiGateway/issues/928

It looks like this PR has introduced changes which broke the tests: https://github.com/SecureApiGateway/conformance-dcr/pull/29

The tests are run as part of the PR checks, but these checks failing do not seem to have prevent the PR from being merged. https://github.com/SecureApiGateway/conformance-dcr/pull/29/checks

Improve CI pipeline to prevent PRs from being merged if they have failing checks.

**Comment by shaunharrisonFR** [comment]
@dbadham-fr @jorgesanchezperez if there's no upcoming work for DCR this week let me know and I'll create a dummy PR to get this pushed through

**Comment by dbadham-fr** [comment]
> @dbadham-fr @jorgesanchezperez if there's no upcoming work for DCR this week let me know and I'll create a dummy PR to get this pushed through

Please do that, not sure when we'll get a chance to work on this project.

**Comment by shaunharrisonFR** [comment]
![image](https://github.com/SecureApiGateway/SecureApiGateway/assets/115990205/7a8d2887-e72a-4db0-bb45-38057341d435)
All three of the steps within `buildAndTest.yml` are now required to pass before you can merge

The steps include, checking the changes, building the docker image and testing the docker image within devenvs via the CF pipeline 

This pipeline only runs when merging to `sbat-master` there is a separate pipeline called `build.yml` which runs when merging to branches other than `sbat-master` think the two have been implemented to avoid having to wait for the tests to run when not merging to main branch
