### ISSUE TITLE
Prepare 'Production' Spec list

### ISSUE THREAD

**Issue by shaunharrisonFR** [SecureApiGateway/SecureApiGateway#989]
For ITSS venture, we'll need a production ready list for the infrastructure, depending on what the customer requires

For internal use - list can be found here: https://docs.google.com/document/d/17te-QA4ho7TjW0U-sY1XmLNCd6ItWWGzoCi0VlBZ77A/edit#heading=h.khbj6f3vn1mu

**Comment by BohoCode** [comment]
Shaun, can you add a description please?

**Comment by shaunharrisonFR** [comment]
Ticket could be closed off as being tracked in jira here - https://bugster.forgerock.org/jira/secure/RapidBoard.jspa?rapidView=923&projectKey=SAPIG&view=detail&selectedIssue=SAPIG-13
